<?php

function motores_multistep_block($op = 'list', $delta = 0, $edit = array()) 
{
	switch( $op )
	{
		case 'list':
	      $blocks[0]['info'] = t('Anuncio multistep');
	      return $blocks;
	      break;
	    case 'view':
	      switch ( $delta )
	      {
			    case 0:
	          $blocks['title'] = '';
	          $blocks['content'] = motores_multistep_markup();
	          break;
	      }
	      return $blocks;
	      break;
	}
}

function motores_multistep_markup()
{
  $t[] = t('Registro'); //0
  $t[] = t('Marca y modelo'); //1
  $t[] = t('A&ntilde;o y submodelo'); //2
  $t[] = t('Detalles'); //3
  $t[] = t('Fotos'); //4
  $t[] = t('Revisi&oacute;n'); //5
  $t[] = t('Pago'); //6
  $t[] = t('Tu anuncio listo'); //7
 /*
  $t[] = t('Marca y modelo'); //0
  $t[] = t('A&ntilde;o y submodelo'); //1
  $t[] = t('Detalles'); //2
  $t[] = t('Fotos'); //3
  $t[] = t('Revisi&oacute;n'); //4
  $t[] = t('Registro'); //5
  $t[] = t('Pago'); //6
  $t[] = t('Tu anuncio listo'); //7
*/  
  $active = -1;
  if ( strpos($_GET['q'], 'node/add/') >= 0 )
  {
    $active = 1;
  }
  if ( arg(2) == 'edit' )
  {
    $active = arg(3);
  }
  if ( arg(0) == 'anuncio_preview' )
  {
    $active = 5;
  }
  if ( arg(0) == 'cart' )
  {
    $active = 6;
  }
  if ( arg(1) == '62' )
  {
    $active = 7;
  }
  
  $r = 
  '<div class="multistep-tabs">
    <ul class="clearfix">';

  foreach ( $t as $i => $step )
  {
    $r .= '<li '.(($active == $i)?'class="active">':'>').($i+1).'. '.$step.'</li>';
  }

  $r .= '</ul>
  </div>';
    
  return $r;
}