<?php
// $Id: taxonomy_super_select.module,v 1.10.2.1 2009/01/21 22:44:21 katou Exp $

/**
 * @file
 *   Changes the default taxonomy select box into checkbox or radio buttons.
 */

function taxonomy_super_select_form_alter(&$form, $form_state, $form_id) {
  drupal_add_css(drupal_get_path('module', 'taxonomy_super_select') .'/taxonomy_super_select.css');
  // Taxonomy Edit Form
  if ($form_id == 'taxonomy_form_vocabulary') {
    $vid = $form['vid']['#value'];
    $vocab = taxonomy_vocabulary_load($vid);
    if ($vocab) {
      $tss = variable_get('taxonomy_super_select_vid_'. $vid, 0);
      // Position the name field higher
      // Add our own submit handler
      $form['#submit'][] = 'taxonomy_super_select_submit';
      // Create fieldset and form elements
      $form['settings']['tss'] = array(
        '#type'         => 'fieldset',
        '#title'        => t('Taxonomy Super Select'),
        '#collapsed'    => ($tss ? FALSE : TRUE),
        '#collapsible'  => TRUE,
        '#tree'         => TRUE,
        '#weight'       => 3,
      );
      // Get list of all content types
      $types = node_get_types('names');
      // Loop through all types that are enabled for this vocab
      foreach ($vocab->nodes as $index => $type) {
        $options[$type] = $types[$type];
      }
     $form['settings']['tss']['taxonomy_super_select_vid_'. $vid]['types'] = array(
        '#type'          => 'checkboxes',
        '#title'         => t('Enable Taxonomy Select for the Vocabulary Content Types Below'),
        '#options'       => $options,                              
        '#default_value' => ($tss ? $tss['types'] : array()),      
        '#weight'        => -1,
      );
      $form['settings']['tss']['taxonomy_super_select_vid_'. $vid]['parents'] = array(
        '#type'           => 'checkbox',
        '#title'          => t('Display parent terms as form items'),
        '#default_value'  => ($tss ? $tss['parents'] : array()),
        '#return_value'   => 1,
        '#weight'         => 0,
        '#description'    => t('Leaving this disabled forces users to select dangling child terms. Useful for grouping terms with descriptive parent terms that are not themselves needed for display.'),
      );

      if (module_exists('taxonomy_image')) {
        $form['settings']['tss']['taxonomy_super_select_vid_'. $vid]['image'] = array(
          '#type' => 'checkbox',
          '#title' => t('Allow Taxonomy Image to provide images with the terms'),
          '#default_value'  => ($tss ? $tss['image'] : array()),
          '#weight' => 2,
          );
      }
    }
  }

  // Node Edit Form
  if (strstr($form_id, '_node_form') && strstr($form['form_id']['#value'], '_node_form')) {
    $content_type = $form['type']['#value'];
    // Get all vocabs for this content type
    $vocabularies = taxonomy_get_vocabularies($content_type);
    $valid_vocabs = array();
    foreach ($vocabularies as $vid => $vocabulary) {
      $tss[$vid] = variable_get('taxonomy_super_select_vid_'. $vid, 0);
      // Only operate on types for a vocabulary that are enabled
      if ($tss[$vid]['types'][$content_type]) {
        // Show radio or checkbox based on the selection type
        $valid_vocabs[$vid] = $vocabulary->multiple ? 'checkbox' : 'radio';
        if ($vocabulary->tags) {
          // Remove any tags from the autocomplete form item (prevent duplicates)
          $tags[$vid] = $form['taxonomy']['tags'][$vid];
          $tags[$vid]['#default_value'] = '';
          $tags[$vid]['#required'] = FALSE;
          $tags[$vid]['#parents'] = array('taxonomy', 'tags', $vid);
          $tags[$vid]['#weight'] = -12;
          $tags[$vid]['#title'] = t('Enter New Tags');
          unset($form['taxonomy']['tags'][$vid]);
        }
        else{
          // Remove the default form rendering except for freetagging vocabs
          unset($form['taxonomy'][$vid]);
        }
      }
    }
    
    // Go through each enabled vocab and create taxonomy super select
    foreach ($valid_vocabs as $vid => $input) {
      // Get root terms for vocabulary only
      if (!$terms = taxonomy_get_tree($vid, 0, -1, 1)) {
        continue;
      }
      $form['taxonomy'][$vid] = _tss_branch($vid, $vocabularies[$vid]);
      if ($tags[$vid]) {
        $form['taxonomy'][$vid]['tags'] = $tags[$vid];
      }
      _tss_next_nested($terms, $vid, $input, $tss, $form['#node'], $form['taxonomy'][$vid]);
    }
  } 
}
/**
 * Recursive function to allow infinite depth vocabularies.
 *
 * @param array &$terms The result of taxonomy_get_tree for the vocabulary's $vid.
 * @param array &$vid The vocabulary to work on. Passed by reference just to keep overhead
 * of copies down.
 * @param array &$input The portion of the vocabulary to look at (parent_type?). Passed by
 * reference just to keep overhead of copies down.
 * @param array $tss These are the settings for this module.
 * @param array &$form_node This is a subsection of $form, namely $form['#node'] should be
 * passed in.
 * @param array &$form_branch This is a subsection of $form. Each iteration adds to the one
 * before, then passes itself as the new branch. _tss_branch() is called for each iteration
 * and appended to it.
 *
 * @return since values are passed in via reference, no return value is required.
 */
function _tss_next_nested(&$terms, &$vid, &$input, $tss, &$form_node, &$form_branch) {
  $fieldweight = 0;
  foreach ($terms as $index => $term) {
    $child = taxonomy_get_children($term->tid, $vid);
    if (count($child)) {
      if ($tss[$vid]['parents']) {
        $term->is_parent = TRUE;
        $term->parent_type  = $input;
        $term->parent_value = $form_node->taxonomy[$term->tid]->tid;
      }
      $form_branch[$term->tid] = _tss_branch($vid, $term, NULL, 'fieldset', ++$fieldweight);
      _tss_next_nested($child, $vid, $input, $tss, $form_node, $form_branch[$term->tid]);
    }
    else {
      if ($value =  $form_node->taxonomy[$term->tid]->tid) {
        $form_branch[$term->tid]['#collapsed'] = FALSE;
      }
      $form_branch[$term->tid] = _tss_branch($vid, $term, $value, $input, $fieldweight++);
    }
  }
}

function _tss_branch($vid, $term, $value = NULL, $type = 'fieldset', $fieldweight = -1) {
  $required = $term->required ? ' <span class="form-required" title="'. t('This field is required.') .'">*</span>' : '';
  switch ($type) {
    case 'fieldset':
      // In this section, $term is actually the vocabulary.
      // Automatically expand required vocabs or if the parent term is selected
      $collapsed = ($required OR $term->parent_value) ? FALSE : TRUE;
      if ($term->help) {
        $help = '<div class="taxonomy-super-select-help">'. $term->help .'</div>';
      }
      else {
        $help = null;
      }
      $form = array(
        '#type' => 'fieldset',
        '#title' => check_plain($term->name) . $required,
        '#collapsible' => TRUE,
        '#collapsed' => $collapsed,
        '#weight' => ($fieldweight >= 0) ? $fieldweight : $term->weight,
        '#parents' => array('taxonomy', $vid),
        '#description' => $term->description . $help,
        '#prefix' => '<div class="taxonomy-super-select-'. ($term->multiple ? 'checkboxes' : 'radios') .'">',
        '#suffix' => '</div>',
      );
      // If we have vocabulary that is single select and not required or is freetagging we need a way to unselect the term
      if ((!$required OR $term->tags) AND $term->multiple == 0 AND $term->module == 'taxonomy') {
        $form['none'] = array(
          '#type' => 'radio',
          '#title' => '<em>'. t('Select None') .'</em>',
          '#return_value' => 0,
          '#default_value' => '',
          '#weight' => -12,
          '#parents' => array('taxonomy', $term->vid),
        );
      }
      if ($term->is_parent) {
        $term->weight = -11;
        $form['parent'] = _tss_branch($term->vid, $term, $term->parent_value, $term->parent_type);
      }
    break;
    case 'radio':
      $form = array(
        '#type' => 'radio',
        '#title' => ($term->is_parent ? '<strong>' : '') . check_plain($term->name) . ($term->is_parent ? '</strong>' : ''),
        '#return_value' => $term->tid,
        '#default_value' => $value,
        '#weight' => ($fieldweight >= 0) ? $fieldweight : $term->weight,
        '#parents' => array('taxonomy', $vid),
      );
    break;
    case 'checkbox':
      $form = array(
        '#type' => 'checkbox',
        '#title' => ($term->is_parent ? '<strong>' : '') . check_plain($term->name) . ($term->is_parent ? '</strong>' : ''),
        '#return_value' => $term->tid,
        '#default_value' => $value,
        '#weight' => ($fieldweight >= 0) ? $fieldweight : $term->weight,       
      );
    break;
  }
  return $form;
}

function taxonomy_super_select_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'validate') {
    // Content type agnostic so far, look for any node that has a vocabulary we handle
    if (count($node->taxonomy)) {
      foreach ($node->taxonomy as $vid => $terms) {
        // Only check vocabularies present
        if (is_numeric($vid)) {
          $tss = variable_get('taxonomy_super_select_vid_'. $vid, FALSE);
          // Validation required
          if ($tss['types'][$node->type]) {
            $vocabulary = taxonomy_vocabulary_load($vid);
            $single = TRUE;
            $has_term = FALSE;
            // Check for freetagging items in the form
            if ($vocabulary->tags) {
              if ($node->taxonomy['tags'][$vid] != '') {
                $free = explode(', ', $node->taxonomy['tags'][$vid]);
                $has_term = TRUE;
              }
            }
            else{
              $free = FALSE;
            }
            if ($vocabulary->required) {
              // Checkboxes
              if ($vocabulary->multiple) {
                // Loop through all the terms as unchecked checkboxes return zero which fools the FAPI required code
                foreach ($terms as $tid => $value) {
                  // Check the freetagging form item for duplicate selected terms
                  if ($vocabulary->tags AND $free) {
                    if ($value) {
                      $this_term = taxonomy_get_term($value);
                      $found = array_search($this_term->name, $free);
                      if ($found !== FALSE) {
                        $duplicates[$vid] .= '"'. check_plain($this_term->name) .'" ';
                      }
                    }
                  }
                  // Regular flat list of terms
                  if ($value > 0) {
                    $has_term = TRUE;
                  }
                }
              }
              else{
                // Radio box that is single select and required
                if ($free AND $terms) {
                  $single = FALSE;
                }
                elseif ($terms) {
                  $has_term = TRUE;
                }
              }
            }
            // Not required phase
            else{
              // Radio Select
              if ($vocabulary->multiple == 0) {
                if ($free AND $terms) {
                  $single = FALSE;
                }
                elseif ($free XOR $terms) {
                  $has_term = TRUE;
                }
              }
              // Checkboxes
              else{
                if (is_array($terms)) {
                  // Freetagging terms are present
                  if (count($free)) {
                    foreach ($terms as $tid => $value) {
                      // Terms set in vocab
                      if ($value > 0) {
                        $single = FALSE;
                      }
                    }
                  }
                }
              } 
            }
            // Catch freetagging vocabs that are single select with a radio checked as well as a new tag
            if (!$single AND !$vocabulary->multiple) {
              form_set_error('taxonomy][tags]['. $vid, t('Only one selection allowed for %vocab', array('%vocab' => $vocabulary->name)));
            }
            // Catch required vocabs with no terms or freetagging entries
            if (!$has_term AND $vocabulary->required) {
              form_set_error('taxonomy]['. $vid, t('%vocab is required.', array('%vocab' => $vocabulary->name)));
            }
            // Catch freetagging terms that are duplicated in the vocab already
            if ($duplicates) {
              // Display duplicate terms for each vocabulary that is freetagging
              foreach ($duplicates as $vid => $terms) {
                // Warn user that they have entered terms that already exist into the free tag field
                form_set_error('taxonomy][tags]['. $vid, t('Tag(s) %dupes already exists in the vocabulary.', array('%dupes' => $terms)));
              }
            }
          }
        }
      }
    }
  }
}

function taxonomy_super_select_submit(&$form, $form_state) {
  $vid = $form['vid']['#value'];
  if (count($form['settings']['tss']['taxonomy_super_select_vid_'. $vid])) {
      $tostore = array(
        'types' => $form['settings']['tss']['taxonomy_super_select_vid_'. $vid]['types']['#value'],
       'parents' => $form['settings']['tss']['taxonomy_super_select_vid_'. $vid]['parents']['#value'],
        'image' => $form['settings']['tss']['taxonomy_super_select_vid_'. $vid]['image']['#value'],
      );
    variable_set('taxonomy_super_select_vid_'. $vid, $tostore);    
  }
  else{
    variable_del('taxonomy_super_select_vid_'. $vid);

    }
  }