<?php

function motores_custom_init() 
{
  drupal_add_js(drupal_get_path('module', 'motores_custom').'/taxonomy_engine.js', $type = 'module', 'header', FALSE, FALSE);
  
  // admin theme for admins
  global $custom_theme;
  global $user;
  if ( 
  ( $user->uid == '1' || in_array('editor', $user->roles) ) 
  && 
  ( arg(2) == 'edit' || arg(1) == 'add' || arg(2) == 'delete' )
  ) 
  {
    $custom_theme = variable_get('admin_theme', '0');
    init_theme();
  }
}

function motores_custom_block($op = 'list', $delta = 0, $edit = array()) {
	/*
	$jeep=explode(',','Caterpillar
	,Clark
	,Crown
	,Hyster
	,Mitsubishi');
	print_r($jeep);
	foreach($jeep as $typed){
		$edit = array('vid' =>  8, 'name' => $typed, 'parent'=>119);
		$status = taxonomy_save_term($edit);
	}*/
	
	switch($op){
		case 'list':
	      $blocks[0]['info'] = t('¿Quieres más info?');
	      $blocks[1]['info'] = t('Mi cuenta');
	      $blocks[2]['info'] = t('Mis anuncios');
	      return $blocks;
	      break;
	    case 'view':
	      switch ( $delta )
	      {
			case 0:
    			  drupal_add_js(drupal_get_path('module', 'motores_custom').'/mensajes_engine.js', $type = 'module', 'header', FALSE, FALSE);
	          $blocks['title'] = t('¿Quieres más info?');
	          $blocks['content'] = motores_custom_get_mensaje_form();
	          break;
	        case 1:
	          $blocks['title'] = t('Mi cuenta');
	          $blocks['content'] = motores_custom_get_micuenta();
	        break;
	        case 2:
	          $blocks['title'] = t('Mis anuncios');
	          $blocks['content'] = motores_custom_get_misanuncios();
	        break;
	      }
	      return $blocks;
	      break;
	}
}



function motores_custom_get_mensaje_form(){
	global $user;
	
	$node = array(
	'uid' => $user->uid,
	'name' => $user->name,
	'type' => 'mensaje'
	);
	
	return drupal_get_form('mensaje_node_form',$node);
}
function motores_custom_form_alter(&$form, &$form_state, $form_id)
{
	if($form_id=='mensaje_node_form')
	{
		$node = node_load(arg(1));
		$form['nuevo_field']=array('#value'=>$node->name,
		                           '#type'=>'hidden');
		$form['nuevo_nid_field']=array('#value'=>$node->title,
		                           '#type'=>'hidden');
		$form['#redirect']='node/'.$node->nid;
	}
}

function motores_custom_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){

	if($op=='insert' && $node->type=='mensaje'){
	  drupal_get_messages($type = NULL, $clear_queue  = TRUE);
	  drupal_set_message('Tu mensaje ha sido enviado al anunciante.');
	  $user_inbox = user_load($node->field_inbox[0]['uid']);
	  $params = array('Mensaje'=>$node->field_mensaje[0]['value']);
	  drupal_mail('motores_custom', 'Mensaje', $user_inbox->mail, user_preferred_language($user_inbox), $params);
	}
	
	if ($op == 'load')
	{
  	switch ($node->type)
  	{
  	  case 'carro':
  	    $node->nombre = $node->field_anio[0]['value'];
  	    $node->nombre_sin_anio = '';
  	    $carro = taxonomy_get_parents_all( $node->field_marca[0]['value'] );
  	    $carro = array_reverse($carro);
  	    foreach ( $carro as $c )
  	    {
  	      $node->nombre .= ' '.$c->name;
  	      $node->nombre_sin_anio .= $c->name.' ';
  	    }
  	    
  	    switch($node->field_tipo_anunio[0]['nid'])
  	    {
	        case 63: //gratuito, 30 dias
	          
	          
	          
	        break;
	        case 53: //basico, 60 dias
	          
	          
	          
	        break;
	        default: // premium
	    
	        break;	
  	    }
  	    //$node->vencimiento
  	    
  	  break;
  	}
	}
}

function motores_custom_mail($key, &$message, $params) {
    
  $message['subject'] = 'Nuevo mensaje en el sitio de motores';
  $message['body'][] = $params['Mensaje'];
  
}


function motores_custom_get_misanuncios(){
	global $user;
	
	$active[] = (arg(2) == 'camioneta') ? 'active' : '';
	$active[] = (arg(2) == 'carro') ? 'active' : '';
	$active[] = (arg(2) == 'moto') ? 'active' : '';
	$active[] = (arg(2) == 'otro') ? 'active' : '';
	$active[] = (arg(2) == 'accesorio') ? 'active' : '';
	
	$output ='<div class="mis-anuncios clearfix">';
	$output .='<div class="camionetas '.$active[0].'">'.l('camioneta','micuenta/'.$user->uid.'/camioneta').'</div>';
	$output .='<div class="carro '.$active[1].'">'.l('carro','micuenta/'.$user->uid.'/carro').'</div>';
	$output .='<div class="moto '.$active[2].'">'.l('moto','micuenta/'.$user->uid.'/moto').'</div>';
	$output .='<div class="otro-tipo '.$active[3].'">'.l('otro','micuenta/'.$user->uid.'/otro').'</div>';
	$output .='<div class="accesorios '.$active[4].'">'.l('accesorios','micuenta/'.$user->uid.'/accesorio').'</div>';
	$output .='</div>';
	
	return $output;
}

function motores_custom_get_micuenta(){
	global $user;
	
	$output = '<div class="item-mis-datos">'.l('Modificar mis datos','user/'.$user->uid.'/edit').'</div>';
	$output .='<div class="item-mis-mensajes">'.l('Mis mensajes ('.motores_custom_get_inbox_total().')','micuenta/inbox').'</div>';
	$output .='<div class="item-ayuda">'.l('Ayuda','ayuda').'</div>';
	$output .='<div class="item-centro-seguridad">'.l('Centro de seguridad','seguridad').'</div>';
	
	return $output;
}

function motores_custom_get_inbox_total(){
	global $user;
	$count = db_result(db_query("SELECT COUNT(DISTINCT(node.nid)) FROM node node 
	 LEFT JOIN content_type_mensaje node_data_field_inbox ON node.vid = node_data_field_inbox.vid
	 WHERE (node.type in ('mensaje')) AND (node_data_field_inbox.field_inbox_uid = $user->uid)
	"));
	
	return $count;
}
