<?php

function motores_custom_menu () {
  $items['crear/anuncio'] = array( 
    'title' => 'Servicios y Tarifas para anunciar tu Carro', 
    'page callback' => 'motores_custom_crear_anuncio', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function motores_custom_block($op = 'list', $delta = 0, $edit = array()) {
	/*
	$jeep=explode(',','Caterpillar
	,Clark
	,Crown
	,Hyster
	,Mitsubishi');
	print_r($jeep);
	foreach($jeep as $typed){
		$edit = array('vid' =>  8, 'name' => $typed, 'parent'=>119);
		$status = taxonomy_save_term($edit);
	}*/
	
	switch($op){
		case 'list':
	      $blocks[0]['info'] = t('¿Quieres más info?');
	      $blocks[1]['info'] = t('Mi cuenta');
	      $blocks[2]['info'] = t('Mis anuncios');
	      return $blocks;
	      break;
	    case 'view':
	      switch ( $delta )
	      {
			case 0:
			  drupal_add_js("$(document).ready(function(){
				var user=$('#edit-nuevo-field').val();
				$('#edit-field-inbox-0-uid-uid').val(user);
				$('#edit-field-inbox-0-uid-uid-wrapper').hide();
				$('#edit-preview').hide();
			});",'inline');
	          $blocks['title'] = t('¿Quieres más info?');
	          $blocks['content'] = motores_custom_get_mensaje_form();
	          break;
	        case 1:
	          $blocks['title'] = t('Mi cuenta');
	          $blocks['content'] = motores_custom_get_micuenta();
	        break;
	        case 2:
	          $blocks['title'] = t('Mis anuncios');
	          $blocks['content'] = motores_custom_get_misanuncios();
	        break;
	      }
	      return $blocks;
	      break;
	}
}

function motores_custom_get_mensaje_form(){
	global $user;
	
	$node = array(
	'uid' => $user->uid,
	'name' => $user->name,
	'type' => 'mensaje'
	);
	
	return drupal_get_form('mensaje_node_form',$node);
}
function motores_custom_form_alter(&$form, &$form_state, $form_id){
	if($form_id=='mensaje_node_form'){
		$node = node_load(arg(1));
		$form['nuevo_field']=array('#value'=>$node->name,
		                           '#type'=>'hidden');
		$form['#redirect']='node/'.$node->nid;
	}
}

function motores_custom_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){

	if($op=='insert' && $node->type=='mensaje'){
	  drupal_get_messages($type = NULL, $clear_queue  = TRUE);
	  drupal_set_message('Tu mensaje ha sido enviado al anunciante.');
	}
}

function motores_custom_get_misanuncios(){
	global $user;
	
	$output ='<div class="mis-anuncios clearfix">';
	$output .='<div class="camionetas">'.l('camioneta','micuenta/'.$user->uid.'/camionetas').'</div>';
	$output .='<div class="carro">'.l('carro','micuenta/'.$user->uid.'/vehiculo').'</div>';
	$output .='<div class="moto">'.l('moto','micuenta/'.$user->uid.'/moto').'</div>';
	$output .='<div class="otro-tipo">'.l('otro','micuenta/'.$user->uid.'/lanchas').'</div>';
	$output .='<div class="accesorios">'.l('accesorios','micuenta/'.$user->uid.'/accesorios').'</div>';
	$output .='</div>';
	
	return $output;
}

function motores_custom_get_micuenta(){
	global $user;
	
	$output = '<div class="item-mis-datos">'.l('Modificar mis datos','user/'.$user->uid.'/edit').'</div>';
	$output .='<div class="item-mis-mensajes">'.l('Mis mensajes ('.motores_custom_get_inbox_total().')','inbox').'</div>';
	$output .='<div class="item-ayuda">'.l('Ayuda','ayuda').'</div>';
	$output .='<div class="item-centro-seguridad">'.l('Centro de seguridad','seguridad').'</div>';
	
	return $output;
}

function motores_custom_get_inbox_total(){
	global $user;
	$count = db_result(db_query("SELECT COUNT(DISTINCT(node.nid)) FROM node node 
	 LEFT JOIN content_type_mensaje node_data_field_inbox ON node.vid = node_data_field_inbox.vid
	 WHERE (node.type in ('mensaje')) AND (node_data_field_inbox.field_inbox_uid = $user->uid)
	"));
	
	return $count;
}

function motores_custom_crear_anuncio(){
	 $output = '
	<h2>Detalles de anuncios</h2>
	<h3>Anuncio gratuito</h3>
	<ul>
	  <li>Máximo 1 anuncio por usuario.</li>
	  <li>Duración 30 dias.</li>
	  <li>Sin renovación.</li>
	  <li>1 fotografía en el detalle del anuncio.</li>
	</ul>
	
	<h3>Anuncio básico</h3>
	<ul>
	  <li>Duración 60 dias.</li>
	  <li>Sin renovación.</li>
	  <li>9 fotogrfías en el detalle del anuncio.</li>
	  <li>Prioridad sobre anuncios gratuitos.</li>
	</ul>
	
	<h3>Anuncio premium</h3>
	<ul>
	  <li>Publicación con distinción preferencial.</li>
	  <li>Prioridad sobre anuncios gratuitos.</li>
	  <li>Tiempo de publicación ilimitado hasta la venta de tu auto <span class="star">*</span></li>
	  <li>32 fotografias en tu anuncio.</li>
	  <li>Estadística de número de visitas a detalle y veces desplegado.</li>
	  <li>Reposicionar tu anuncio <span class="star">*</span><span class="star">*</span></li>
	</ul>
	
	<div class="politics">
	<p><span class="star">*</span> Publicación siempre y cuando el cliente extienda manualmente la publicación al menos una vez cada 30.</p>
	<p><span class="star">*</span><span class="star">*</span> El servicio de reposicionar y publicar nuevamente tu anuncio al principio de todos los 
	anuncios premium es como volver a publicar tu auto nuevamente para ganar posiciones sobre todos los vehiculos.</p>
	</div>
	
	<div class="table">
	<table>
	<tbody>
	 <tr class="lastrow">
	  <td>Costo por reposicionar anuncio</td>
	  <td>$90</td>
	  <td></td>
	  <td class="lastcol"></td>
	 </tr>
	 </tbody>
	 </table>
	</div>
	
	<div class="tarifas-de-anuncio">
	<h2>Tarifas de anuncio</h2>
	
	<div class="table">
	<table>
	<thead>
   <tr>
    <th class="tipo">Tipo de anuncio</th>
    <th>Gratuito</th>
    <th>Basico</th>
    <th class="lastcol">Premium</th>
   </tr>
   </thead>
  <tbody>
   <tr>
    <td>Costo por anuncio</td>
    <td>$0</td>
    <td>$100</td>
    <td class="lastcol">$230</td>
   </tr>
  
  <tr>
    <td>Tiempo de publicaci&oacute;n</td>
    <td>30 dias</td>
    <td>60 dias</td>
    <td class="lastcol">Ilimitado</td>
   </tr>
  
  <tr>
    <td>Foto</td>
    <td>&nbsp;</td>
    <td><span class="checked">*</span></td>
    <td class="lastcol">Anuncio destacado</td>
   </tr>
  
  <tr>
    <td>Reposicionar anuncio</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td class="lastcol"><span class="checked">*</span></td>
   </tr>
  
  <tr>
    <td>Fotografias por anuncio</td>
    <td>1</td>
    <td>9</td>
    <td class="lastcol">32</td>
   </tr>
  
  <tr>
    <td>Prioridad del anuncio sobre los demás</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td class="lastcol"><span class="checked">*</span></td>
   </tr>
  
  <tr>
    <td>Distintivo de anuncio</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td class="lastcol"><span class="checked">*</span></td>
   </tr>
  
  <tr>
    <td>Estadisticas de anuncio</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td class="lastcol"><span class="checked">*</span></td>
   </tr>
  
  <tr>
    <td>Anuncios premitidos por pago</td>
    <td>1</td>
    <td>1</td>
    <td class="lastcol">1</td>
   </tr>
  
  <tr class="lastrow">
    <td>&nbsp;</td>
    <td class="quiero">'.l('¡Quiero esto!','node/add/carro').'</td>
    <td class="quiero"><a href="#">¡Quiero esto!</a></td>
    <td class="quiero lastcol"><a href="#">¡Quiero esto!</a></td>
   </tr>
	 </tbody>
	 </table>
	 </div>
	</div>
	
	';
	
	return $output;
}