<?php

function motores_custom_block($op = 'list', $delta = 0, $edit = array()) {
	switch($op){
		case 'list':
	      $blocks[0]['info'] = t('¿Quieres más info?');
	      return $blocks;
	      break;
	    case 'view':
	      switch ( $delta )
	      {
			case 0:
	          $blocks['title'] = t('¿Quieres más info?');
	          $blocks['content'] = motores_custom_get_mensaje_form();
	          break;
	      }
	      return $blocks;
	      break;
	}
}

function motores_custom_get_mensaje_form(){
	global $user;
	
	$node = array(
	'uid' => $user->uid,
	'name' => $user->name,
	'type' => 'mensaje'
	);
	
	return drupal_get_form('mensaje_node_form',$node);
}
function motores_custom_form_alter(&$form, &$form_state, $form_id){
	if($form_id=='mensaje_node_form'){
		$node = node_load(arg(1));
		$form['nuevo_field']=array('#value'=>$node->name,
		                           '#type'=>'hidden');
		drupal_add_js("$(document).ready(function(){
			var user=$('#edit-nuevo-field').val();
			$('#edit-field-inbox-0-uid-uid').val(user);
		});",'inline');
		$form['#redirect']='node/'.$node->nid;
	}
}

function motores_custom_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){

	if($op=='insert' && $node->type=='mensaje'){
	
	}
}