<?php

function motores_calculadora_menu () {
  $items['calcular/seguros'] = array(  
    'page callback' => 'calcular_seguros', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/*
function motores_calculadora_init() {
    drupal_add_js(drupal_get_path('module', 'motores_custom').'/taxonomy_engine.js', $type = 'module', 'header', FALSE, FALSE);
}
*/

function motores_calculadora_block($op = 'list', $delta = 0, $edit = array()) {
	
	switch($op){
		case 'list':
	      $blocks[0]['info'] = t('Calculadora financiera');
	      return $blocks;
	      break;
	    case 'view':
	      switch ( $delta )
	      {
			 case 0:
		          drupal_add_js(drupal_get_path('module', 'motores_calculadora').'/calculadora_engine.js', $type = 'module', 'header', FALSE, FALSE);
		          $blocks['title'] = t('Calculadora');
		          $blocks['content'] = motores_calculadora_get_calculadora();
		        break;
	      }
	      return $blocks;
	      break;
	}
}

function motores_calculadora_get_calculadora(){
	$output = '<div id="calcu-form"><form>
	  
	  <h2>Datos del veh&iacute;culo</h2>
   		<div class="calc-item">
		  <label>Marca:</label>
		  <select name="marca" id="marca">
		    <option value="Volskwagen">Volskwagen</option>
		    <option value="Seat">Seat</option>
		  </select>
		</div>
		<div class="calc-item">
		  <label>Año:</label>
		  <select name="anio" id="anio">
		    <option value="1997">1997</option>
		    <option value="1998">1998</option>
		  </select>
		</div>
		<div class="calc-item">
		  <label>Línea - Versión - Descripción:</label>
		  <select name="version" id="version">
		    <option value="Ibiza">Ibiza</option>
		    <option value="Cabrio">Cabrio</option>
		  </select>
		</div>
		
		  <h2>Datos del Crédito:</h2>
		
		<div class="calc-item">
		  <label>Precio de venta al contado:</label>
		  <input type="text" size="20" name="precio" id="precio" />
		</div>
		<div class="calc-item red">
		  <label>Enganche:</label>
		  <input type="text" size="20" name="enganche" id="enganche" />
		</div>
		
	<input type="button" value="Calcular" id="submit-calc" />
	</form>
	<div id="result"></div></div>';
	
	return $output;
}



function motores_calculadora_calcular(){
	$marcas = array('ACURA',
	'ALFA ROMEO',
	'AUDI',
	'BMW',
	'CADILLAC',
	'CHEVROLET',
	'CHRYSLER',
	'DODGE',
	'FERRARI',
	'FIAT',
	'FORD',
	'GMC',
	'HONDA',
	'HUMMER',
	'INFINITI',
	'JAGUAR',
	'JEEP',
	'LAND ROVER',
	'LINCOLN',
	'LOTUS',
	'MASERATI',
	'MAZDA',
	'MERCEDES',
	'MERCURY',
	'MG',
	'MINI',
	'MITSUBISHI',
	'NISSAN',
	'PEUGEOT',
	'PONTIAC',
	'PORSCHE',
	'RENAULT',
	'ROVER',
	'SAAB',
	'SEAT',
	'SMART',
	'SSANGYONG',
	'SUBARU',
	'SUZUKI',
	'TOYOTA',
	'VOLKSWAGEN',
	'VOLVO');
}