<?php

function motores_multistep_block($op = 'list', $delta = 0, $edit = array()) 
{
	switch( $op )
	{
		case 'list':
	      $blocks[0]['info'] = t('Anuncio multistep');
	      return $blocks;
	      break;
	    case 'view':
	      switch ( $delta )
	      {
			    case 0:
	          $blocks['title'] = '';
	          $blocks['content'] = motores_multistep_markup();
	          break;
	      }
	      return $blocks;
	      break;
	}
}

function motores_multistep_markup()
{
  //drupal_add_js( drupal_get_path('module', 'motores_multistep').'/motores_multistep.js', 'module' );
  
  $t[] = t('Marca y modelo');
  $t[] = t('A&ntilde;o y submodelo');
  $t[] = t('Detalles');
  $t[] = t('Fotos');
  $t[] = t('Revisi&oacute;n');
  $t[] = t('Registro');
  $t[] = t('Pago');
  $t[] = t('Tu anuncio listo');
  
  if ( $_GET['q'] == 'node/add/vehiculo' )
  {
    $active = 0;
  }
  else if ( arg(2) == 'edit' )
  {
    $active = arg(3) - 1;
  }
  
  $r = 
  '<div class="multistep-tabs clearfix">
    <ul>';

  foreach ( $t as $i => $step )
  {
    $r .= '<li '.(($active == $i)?'class="active">':'>').($i+1).'. '.$step.'</li>';
  }

  $r .= '</ul>
  </div>';
    
  return $r;
}