<?php

function motores_register_block( $op = 'list', $delta = 0, $edit = array() )
{
  switch( $op )
  {
  	case 'list':
        $blocks[0]['info'] = t('Login stuff');
        return $blocks;
        break;
      case 'view':
        switch ( $delta )
        {
  		    case 0:
            $blocks['title'] = '';
            $blocks['content'] = motores_register_markup();
            break;
        }
        return $blocks;
        break;
  }
}

function motores_register_markup()
{
  global $user;
  
  if ( $user->uid )
  {
    $dude = user_load($user->uid);
    $r = 'Hola <strong>'.$dude->profile_nombre.'</strong> | '.l(t('Mi cuenta'), 'micuenta' ).' | '.l( t('Cerrar sesi&oacute;n'), 'logout', array('html'=>true) );
  }
  else
  {
    $r = l( t('Iniciar sesi&oacute;n'), 'user/login', array('html'=>true) );
  }
  
  return $r;
}

function motores_register_form_alter( &$form, &$form_state, $form_id )
{
  if ( arg(0) == 'admin' ) return;
  if ( $form_id == 'user_login' )
  {
    drupal_add_js(drupal_get_path('module', 'motores_register').'/login_engine.js', $type = 'module', 'header', FALSE, FALSE);
    
    $form['#prefix'] = 
      '<div id="login-before">
          <h2>'.t('&iquest;Buscas anunciar? Reg&iacute;strate').'</h2>
          <div class="help">'.t('Estimado cliente, para que puedas publicar tus anuncios necesitas registrarte.').'</div>
          '.l( t('Reg&iacute;strate'), 'user/register', array('html'=>true)).'
       </div>';
    $form['help'] = array(
      '#value' => '<h2>'.t('Accede a tu cuenta').'</h2><div class="help">'.t('Estimado cliente, para hacer uso de nuestros sistemas de publicaci&oacute;n es necesario que ingreses tu correo electr&oacute;nico y tu contrase&ntilde;a.').'</div>',
      '#weight' => -99
    );
    $form['forgot'] = array(
      '#value' => '<div class="forgot">'.l( t('&iquest;Haz olvidado tu contrase&ntilde;a?'), 'user/password', array('html'=>true)).'</div>',
      '#weight' => 1
    );
    $form['submit']['#value'] = t('Continuar');
  }
  else if ( $form_id == 'user_register' )
  {
    drupal_add_js(drupal_get_path('module', 'motores_register').'/register_engine.js', $type = 'module', 'header', FALSE, FALSE);
    
    // weights
    $form['account']['#weight'] = 29;
    
    print_r($form);
    // Prefix de forma
    if (isset($_GET['destination'])) 
    {
      $params = array('query'=>'destination='.$_GET['destination']);
    }
    else
    {
      $params = array();
    }
    $form['#prefix'] = 
      '<div id="register-msg">'.
      t('&iquest;Est&aacute;s registrado y quieres hacer un cambio a tu cuenta?').' '.
      l( t('Accede a tu cuenta'), 'user/login', $params ).
      '</div>';
    
    // titles
    unset( $form['account']['#title'] );
    unset( $form['Datos personales']['#title'] );
    unset( $form['Datos personales']['profile_tel1_codigo']['#title'] );
    unset( $form['Datos personales']['profile_tel1_num']['#title'] );
    unset( $form['Datos personales']['profile_tel2_codigo']['#title'] );
    unset( $form['Datos personales']['profile_tel2_num']['#title'] );
    
    $form['Datos personales']['profile_nombre']['#prefix'] = '<h2>'.t('Cu&eacute;ntanos de ti').'</h2>';
    $form['account']['name']['#prefix'] = '<h2>'.t('Escoge tu contrase&ntilde;a').'</h2>';
    
    $form['account']['pass']['#suffix'] = '<div id="usa">* '.t('Usa un password diferente al de tu cuenta de correo.').'</div>';
    
    $form['Datos personales']['profile_tel1_tipo']['#prefix'] = '<div id="tel1" class="clearfix">';
    $form['Datos personales']['profile_tel1_num']['#suffix'] = '</div>';
    
    $form['Datos personales']['profile_tel2_tipo']['#prefix'] = '<div id="tel2" class="clearfix">';
    $form['Datos personales']['profile_tel2_num']['#suffix'] = '</div>';
    
    $form['Datos personales']['profile_sexo']['#type'] = 'radios';
    
    $form['Datos personales']['profile_estado']['#prefix'] = '<div class="bar">&nbsp;</div>';
    
    // Submit
    $form['submit']['#prefix'] = '<div class="bar">&nbsp;</div><div id="btns">';
    $form['submit']['#value'] = t('Continuar');
    
    $form['borrar'] = array(
      '#weight' => $form['submit']['#weight']+1,
      '#value' => t('Borrar'),
      '#type' => 'button',
      '#suffix' => '</div>',
      '#submit' => false
    );
  }
  else if ( $form_id == 'user_profile_form' )
  {
    drupal_add_js(drupal_get_path('module', 'motores_register').'/modif_engine.js', $type = 'module', 'header', FALSE, FALSE);
    
    //print_r($form);
    unset( $form['enable_pm_mail'] );
    unset( $form['account']['#title'] );
    unset( $form['Datos personales']['#title'] );
    unset( $form['Datos personales']['profile_tel1_codigo']['#title'] );
    unset( $form['Datos personales']['profile_tel1_num']['#title'] );
    unset( $form['Datos personales']['profile_tel2_codigo']['#title'] );
    unset( $form['Datos personales']['profile_tel2_num']['#title'] );
    
    $form['account']['mail']['#type'] = 'hidden';
    
    $form['Datos personales']['profile_tel1_tipo']['#prefix'] = '<div id="tel1" class="clearfix">';
    $form['Datos personales']['profile_tel1_num']['#suffix'] = '</div>';
    
    $form['Datos personales']['profile_tel2_tipo']['#prefix'] = '<div id="tel2" class="clearfix">';
    $form['Datos personales']['profile_tel2_num']['#suffix'] = '</div>';
    
    $form['Datos personales']['profile_sexo']['#type'] = 'radios';
    
    $form['Datos personales']['profile_estado']['#prefix'] = '<div class="bar"></div>';
    $form['account']['pass']['#prefix'] = '<div class="bar"></div>';
    
    $form['Datos personales']['profile_nombre']['#prefix'] = '<h2>'.t('Datos personales').'</h2>';
    
    $form['submit']['#prefix'] = '<div class="bar">&nbsp;</div>';
    $form['submit']['#value'] = t('Actualizar datos');
  }
}