<?php

function motores_menus_block($op = 'list', $delta = 0, $edit = array()) 
{
	switch( $op )
	{
		case 'list':
	      $blocks[0]['info'] = t('Menus scroll');
	      return $blocks;
	      break;
	    case 'view':
	      switch ( $delta )
	      {
			  case 0:
	          	$blocks['title'] = '';
	          	$blocks['content'] = motores_menus_markup();
	          break;
	      }
	      return $blocks;
	      break;
	}
}

function motores_menus_markup()
{
  drupal_add_js(drupal_get_path('module', 'motores_menus').'/menus_engine.js', $type = 'module', 'header', FALSE, FALSE);
  
  
  
  // // // // // 
  
  $r = '<div id="motores-menus" class="clearfix">
          <a id="1" href="javascript:void(0)">'.t('Autos & Camionetas').'</a>
          <a id="2" href="javascript:void(0)">'.t('Accesorios').'</a>
          <a id="3" href="javascript:void(0)">'.t('Motocicletas').'</a>
          <a id="4" href="javascript:void(0)">'.t('Extremo').'</a>
          <a id="5" href="javascript:void(0)">'.t('Lanchas').'</a>
          <a id="6" href="javascript:void(0)">'.t('Otros vehículos').'</a>
        </div>
        <div id="autos-camionetas" class="clearfix panel">'.motores_menus_vocabulary('3').'</div>
        <div id="motos" class="clearfix panel">'.motores_menus_vocabulary('4').'</div>
        <div id="lanchas" class="clearfix panel">'.motores_menus_vocabulary('5').'</div>
        <div id="extremo" class="clearfix panel">'.motores_menus_vocabulary('9').'</div>
        <div id="otros" class="clearfix panel">'.motores_menus_vocabulary('8').'</div>
        ';
  return $r;
}

function motores_menus_vocabulary( $vid )
{
  $v = taxonomy_get_tree($vid, 0, -1, 1);
  
  $carros = '<div class="col">';
  foreach ( $v as $i => $car )
  {
    $attr = array();
    
    $first = $i < 10;
    $last = ($i+1) % 10 == 0 && $i < count($v)-1;
    
    if ( $first ) $attr['class'] = 'first'; 
    if ( $last ) $attr['class'] .= ' last';
    
    $neim = ( strlen($car->name) > 13 ) ? substr($car->name,0,10).'...' : $car->name;
    
    $carros .= l( $neim, 'midq', array('attributes'=>$attr, 'query'=>'t='.$car->tid ) );
    if ( $last ) $carros .= '</div><div class="col">';
  }
  $carros .= '</div>';
  
  return $carros;
}

function motores_menus_menu()
{
  $items['midq'] = array(
  	'title' => t(''),
    'page callback' => 'motores_busqueda_inter', 
    'access arguments' => array('access content'),  
    'type' => MENU_CALLBACK,
  );
  return $items;
}


function motores_busqueda_inter(){
 
  unset($_SESSION['search_form_state']['estado']);
  unset($_SESSION['search_form_state']['marcas'] );
  unset($_SESSION['search_form_state']['precio_min']);
  unset($_SESSION['search_form_state']['precio_max']);
  unset($_SESSION['search_form_state']['anio_min']);
  unset($_SESSION['search_form_state']['anio_max']);
  unset($_SESSION['search_form_state']['km_min'] );
  unset($_SESSION['search_form_state']['km_max']);
  unset($_SESSION['search_form_state']['keywords']);

  
  
  $tids = $_GET['t'];
  $query = "SELECT DISTINCT n.nid FROM {node} n ";
  $query .= "INNER JOIN {term_node} t ON n.vid = t.vid ";
  
  $query .= "WHERE ";
  $where = array();
  $arguments = array();
  
  $where[] = "t.tid IN (".db_placeholders($tids).") ";
  $arguments = $tids;
  
  $query .= implode(" AND ", $where);
 
 	$db_result = db_query(db_rewrite_sql($query), $arguments);
    $result = array();
    while ($res = db_fetch_object($db_result)) 
    {
      $result[] = $res;
    }
    
    foreach ( $result as $r )
    {
      $nids[] = $r->nid;
    }
    
     if ( $nids )
  {
    //$view = views_get_view( 'busqueda' );
    //$view->set_arguments( array(implode(',',$nids)) );
    //echo $view->execute_display( 'default' );
    $_SESSION['search_results'] = implode(',',$nids);
  }
  else
  {
    $_SESSION['search_results'] = '';
  }
  
  drupal_goto('busqueda');


}