<?php

/**
 * motores_anuncio.module ---------
 *
 * Controla todo lo que tiene que ver con un anuncio y su duenio.
 * Fechas de vigencia, form alters, etc.
 *
 * Tambien despliega datos importantes en celdas del dashboard.
 *
 **/


function motores_anuncio_menu()
{
  $items['admin/settings/motores_anuncio'] = array(
    'title' => t('Proceso de anuncio'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('motores_anuncio_settings'),
    'access arguments' => array('administer anuncio process')
  );
  
  $items['anuncio/crear'] = array(
    'title' => t('Proceso de anuncio'),
    'page callback' => 'motores_anuncio_configure_cart',
    'access arguments' => array('access content')
  );
  
  $items['anuncio/borrar'] = array(
    'title' => t('Borrar anuncio'),
    'page callback' => 'motores_anuncio_borrar',
    'access arguments' => array('access content')
  );
  
  return $items;
}

function motores_anuncio_perm()
{
  return array('administer anuncio process');
}

function motores_anuncio_settings()
{
  $form = array();
  $form['motores_anuncio_eula'] = array(
    '#type' => 'textarea',
    '#default_value' => variable_get( 'motores_anuncio_eula', '' ),
    '#title' => t('End User License Agreement')
  );
  
  return system_settings_form( $form );
}

function motores_anuncio_form_alter( &$form, &$form_state, $form_id )
{
  global $user;
  if ( $user->uid != 1 && !in_array('editor', $user->roles) )
  {
    switch ($form_id)
    {
    
    
    /************************************
    *               CARROS              *
    ************************************/
    
      case 'carro_node_form':
        
        drupal_add_js(drupal_get_path('module', 'motores_anuncio').'/anuncio_engine.js', $type = 'module', 'header', FALSE, FALSE);
        
        //print_r($form);exit;
        
        // container div
        $form['#prefix'] = '<div class="anuncio600">';
        $form['#suffix'] = '</div>';
        
        // botones
        unset($form['buttons']['save']);
        unset($form['buttons']['delete']);
        unset($form['buttons']['previous']);
        if (isset($form['buttons']['next']))
        { 
          $form['buttons']['next']['#value'] = t('Continuar');
        }
        else
        {
          $form['buttons']['done']['#value'] = t('Continuar');
          $form['#redirect'] = 'anuncio_preview/'.$form['#node']->nid;
        }
        
        
        
        /**********
        PASO 2
        **********/
        unset($form['field_tipo_anunio']);
        //$form['field_vigencia']['#type'] = 'hidden';
        $form['group_marca_modelo']['#prefix'] = '<h2>'.t('Paso 2: Marca y Modelo').'</h2>';
        $form['group_marca_modelo']['field_marca']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y modelo del vehículo que desea vender.').'</p></div>';
        $form['group_marca_modelo']['#suffix'] =
          '<fieldset>
            <div class="nn clear-block"><div class="num">2</div><p>'.t('Aceptar el reglamento de publicación de anuncios en Mercado Absoluto Vehículos.').'</p></div>
          
            <div class="form-item">
              <textarea id="eula" readonly="readonly">'.variable_get( 'motores_anuncio_eula', '' ).'</textarea>
              <input type="checkbox"/> '.t('He leído y acepto las condiciones del reglamento.').'
            </div>
          </fieldset>';
        
        
        /**********
        PASO 3
        **********/
        $form['group_anio_submodelo']['#prefix'] = '<h2>'.t('Paso 3: Año y Submodelo').'</h2>';
        $form['group_anio_submodelo']['field_anio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y sub-modelo del vehículo que desea:').'</p></div>';
        
        
        /**********
        PASO 4
        **********/
        $form['group_detalles']['#prefix'] = 
        '<h2>'.t('Paso 4: Detalles').'</h2><p>'.t('Llena los siguientes datos describiendo las características del vehículo que deseas vender.
        Los campos obligatorios se indican con').' (<span class="form-required">*</span>).</p>';
        $form['group_detalles']['field_precio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Datos del vehículo').'</p></div>';
         /* <div class="nn form-item clear-block">
          <div class="preview-field">Marca: </div>
          <div class="preview-field">Submodelo: <span>'.$form['#node']->field_version[0]['value'].'</span></div>
          <div class="preview-field">Modelo: </div>
          <div class="preview-field">Año: <span>'.$form['#node']->field_anio[0]['value'].'</span></div>
          </div>
          ';*/
        $form['body_field']['#prefix'] = '<fieldset><div class="nn clear-block"><div class="num">4</div><p>'.t('Describe tu auto').'</p></div>';
        $form['body_field']['#suffix'] = '</fieldset>';
        unset($form['body_field']['format']);
        
        $form['group_equipo']['field_cristales']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">2</div><p>'.t('Equipo').'</p></div>';
        $form['group_describe']['field_especiales']['#prefix'] = 
         '<div class="nn clear-block"><div class="num">3</div><p>'.t('Opciones especiales de venta').'</p></div>';
        
        if (motores_anuncio_is_cuenta_agencia($user))
        {
          $form['group_liga']['field_liga_agencia']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">5</div><p>'.t('Proporciona la liga del sitio de tu agencia').'</p></div>';
        }
        else
        {
          unset($form['group_liga']);
        }
        
        /**********
        PASO 5
        **********/
        
        // las fotos se tratan especialmente
        if ( arg(3) != '4' )
        {
          unset( $form['group_fotos'] );
          unset( $form['group_logo'] );
        }
        else
        {
          // validar si puede subir logo de agencia
          if ( !(in_array('agencia nuevos', $user->roles) || in_array('agencia otros', $user->roles) ||
                in_array('agencia usados', $user->roles) || in_array('lote usados', $user->roles)) )
          {
            unset($form['group_logo']);
            unset($form['group_liga']);
          }
          
          $form['group_fotos']['field_imagenes']['field_imagenes_add_more']['#value'] = t('Agregar otra foto');
          $form['group_fotos']['#prefix'] = 
          '<h2>'.t('Paso 5: Fotos').'</h2><p>'.t('Sube las fotos del automóvil aquí, en formato JPG, GIF o PNG. Recuerda que las puedes subir después.').'</p>';
          $form['group_fotos']['field_imagenes']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">1</div><p>'.t('Fotos del vehículo').'</p></div>';
          $form['group_logo']['field_logo_agencia']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">2</div><p>'.t('Logotipo de agencia').'</p></div>';
          
          //print_r($form);exit;
        }
        break;
        
        
        
    /************************************
    *               MOTOS               *
    ************************************/
    
      case 'moto_node_form':
      
        drupal_add_js(drupal_get_path('module', 'motores_anuncio').'/anuncio_engine.js', $type = 'module', 'header', FALSE, FALSE);
        
        //print_r($form);exit;
        
        // container div
        $form['#prefix'] = '<div class="anuncio600">';
        $form['#suffix'] = '</div>';
        
        if(arg(3)!=3){
        	unset($form['body_field']);
        }
        
        // botones
        unset($form['buttons']['save']);
        unset($form['buttons']['delete']);
        unset($form['buttons']['previous']);
        if (isset($form['buttons']['next']))
        { 
          $form['buttons']['next']['#value'] = t('Continuar');
        }
        else
        {
          $form['buttons']['done']['#value'] = t('Continuar');
          $form['#redirect'] = 'anuncio_preview/'.$form['#node']->nid;
        }
        
        
        
        /**********
        PASO 2
        **********/
        unset($form['field_tipo_anunio']);
        //$form['field_vigencia']['#type'] = 'hidden';
        $form['group_marca_modelo']['#prefix'] = '<h2>'.t('Paso 2: Marca y Modelo').'</h2>';
        $form['group_marca_modelo']['field_marca_moto']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y modelo del vehículo que desea vender.').'</p></div>';
        $form['group_marca_modelo']['#suffix'] =
          '<fieldset>
            <div class="nn clear-block"><div class="num">2</div><p>'.t('Aceptar el reglamento de publicación de anuncios en Mercado Absoluto Vehículos.').'</p></div>
          
            <div class="form-item">
              <textarea id="eula" readonly="readonly">'.variable_get( 'motores_anuncio_eula', '' ).'</textarea>
              <input type="checkbox"/> '.t('He leído y acepto las condiciones del reglamento.').'
            </div>
          </fieldset>';
        
        
        /**********
        PASO 3
        **********/
        $form['group_anio_submodelo']['#prefix'] = '<h2>'.t('Paso 3: Año y Submodelo').'</h2>';
        $form['group_anio_submodelo']['field_anio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y sub-modelo del vehículo que desea:').'</p></div>';
        
        
        /**********
        PASO 4
        **********/
        $form['group_detalles']['#prefix'] = 
        '<h2>'.t('Paso 4: Detalles').'</h2><p>'.t('Llena los siguientes datos describiendo las características del vehículo que deseas vender.
        Los campos obligatorios se indican con').' (<span class="form-required">*</span>).</p>';
        $form['group_detalles']['field_precio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Datos del vehículo').'</p></div>';
         /* <div class="nn form-item clear-block">
          <div class="preview-field">Marca: </div>
          <div class="preview-field">Submodelo: <span>'.$form['#node']->field_version[0]['value'].'</span></div>
          <div class="preview-field">Modelo: </div>
          <div class="preview-field">Año: <span>'.$form['#node']->field_anio[0]['value'].'</span></div>
          </div>
          ';*/
         $form['body_field']['#prefix'] = '<fieldset><div class="nn clear-block"><div class="num">2</div><p>'.t('Describe tu moto').'</p></div>';
        $form['body_field']['#suffix'] = '</fieldset>';
        unset($form['body_field']['format']);
                
        if (motores_anuncio_is_cuenta_agencia($user))
        {
          $form['group_liga']['field_liga_agencia']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">3</div><p>'.t('Proporciona la liga del sitio de tu agencia').'</p></div>';
        }
        else
        {
          unset($form['group_liga']);
        }
        
        /**********
        PASO 5
        **********/
        
        // las fotos se tratan especialmente
        if ( arg(3) != '4' )
        {
          unset( $form['group_fotos'] );
          unset( $form['group_logo'] );
        }
        else
        {
          // validar si puede subir logo de agencia
          if ( !(in_array('agencia nuevos', $user->roles) || in_array('agencia otros', $user->roles) ||
                in_array('agencia usados', $user->roles) || in_array('lote usados', $user->roles)) )
          {
            unset($form['group_logo']);
            unset($form['group_liga']);
          }
          
          $form['group_fotos']['field_imagenes']['field_imagenes_add_more']['#value'] = t('Agregar otra foto');
          $form['group_fotos']['#prefix'] = 
          '<h2>'.t('Paso 5: Fotos').'</h2><p>'.t('Sube las fotos del automóvil aquí, en formato JPG, GIF o PNG. Recuerda que las puedes subir después.').'</p>';
          $form['group_fotos']['field_imagenes']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">1</div><p>'.t('Fotos del vehículo').'</p></div>';
          $form['group_logo']['field_logo_agencia']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">2</div><p>'.t('Logotipo de agencia').'</p></div>';
          
          //print_r($form);exit;
        }
        break;
        
        
    /************************************
    *              LANCHAS              *
    ************************************/
    
      case 'lancha_node_form':
    
        drupal_add_js(drupal_get_path('module', 'motores_anuncio').'/anuncio_engine.js', $type = 'module', 'header', FALSE, FALSE);
        
        //print_r($form);exit;
        
        // container div
        $form['#prefix'] = '<div class="anuncio600">';
        $form['#suffix'] = '</div>';
        
        
         if(arg(3)!=3){
        	unset($form['body_field']);
        }
        
        // botones
        unset($form['buttons']['save']);
        unset($form['buttons']['delete']);
        unset($form['buttons']['previous']);
        if (isset($form['buttons']['next']))
        { 
          $form['buttons']['next']['#value'] = t('Continuar');
        }
        else
        {
          $form['buttons']['done']['#value'] = t('Continuar');
          $form['#redirect'] = 'anuncio_preview/'.$form['#node']->nid;
        }
        
        
        
        /**********
        PASO 2
        **********/
        unset($form['field_tipo_anunio']);
        //$form['field_vigencia']['#type'] = 'hidden';
        $form['group_marca_modelo']['#prefix'] = '<h2>'.t('Paso 2: Marca y Modelo').'</h2>';
        $form['group_marca_modelo']['field_marca_lancha']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y modelo del vehículo que desea vender.').'</p></div>';
        $form['group_marca_modelo']['#suffix'] =
          '<fieldset>
            <div class="nn clear-block"><div class="num">2</div><p>'.t('Aceptar el reglamento de publicación de anuncios en Mercado Absoluto Vehículos.').'</p></div>
          
            <div class="form-item">
              <textarea id="eula" readonly="readonly">'.variable_get( 'motores_anuncio_eula', '' ).'</textarea>
              <input type="checkbox"/> '.t('He leído y acepto las condiciones del reglamento.').'
            </div>
          </fieldset>';
        
        
        /**********
        PASO 3
        **********/
        $form['group_anio_submodelo']['#prefix'] = '<h2>'.t('Paso 3: Año y Submodelo').'</h2>';
        $form['group_anio_submodelo']['field_anio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y sub-modelo del vehículo que desea:').'</p></div>';
        
        
        /**********
        PASO 4
        **********/
        $form['group_detalles']['#prefix'] = 
        '<h2>'.t('Paso 4: Detalles').'</h2><p>'.t('Llena los siguientes datos describiendo las características del vehículo que deseas vender.
        Los campos obligatorios se indican con').' (<span class="form-required">*</span>).</p>';
        $form['group_detalles']['field_anuncio_estado']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Datos del vehículo').'</p></div>';
         /* <div class="nn form-item clear-block">
          <div class="preview-field">Marca: </div>
          <div class="preview-field">Submodelo: <span>'.$form['#node']->field_version[0]['value'].'</span></div>
          <div class="preview-field">Modelo: </div>
          <div class="preview-field">Año: <span>'.$form['#node']->field_anio[0]['value'].'</span></div>
          </div>
          ';*/
         $form['body_field']['#prefix'] = '<fieldset><div class="nn clear-block"><div class="num">4</div><p>'.t('Describe tu lancha').'</p></div>';
        $form['body_field']['#suffix'] = '</fieldset>';
        unset($form['body_field']['format']);
        
        $form['group_equipo']['field_blindaje']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">2</div><p>'.t('Equipo').'</p></div>';
          
        $form['group_opciones']['field_especiales']['#prefix'] = 
         '<div class="nn clear-block"><div class="num">3</div><p>'.t('Opciones especiales de venta').'</p></div>';
        
        if (motores_anuncio_is_cuenta_agencia($user))
        {
          $form['group_liga']['field_liga_agencia']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">5</div><p>'.t('Proporciona la liga del sitio de tu agencia').'</p></div>';
        }
        else
        {
          unset($form['group_liga']);
        }
        
        /**********
        PASO 5
        **********/
        
        // las fotos se tratan especialmente
        if ( arg(3) != '4' )
        {
          unset( $form['group_fotos'] );
          unset( $form['group_logo'] );
        }
        else
        {
          // validar si puede subir logo de agencia
          if ( !(in_array('agencia nuevos', $user->roles) || in_array('agencia otros', $user->roles) ||
                in_array('agencia usados', $user->roles) || in_array('lote usados', $user->roles)) )
          {
            unset($form['group_logo']);
            unset($form['group_liga']);
          }
          
          $form['group_fotos']['field_imagenes']['field_imagenes_add_more']['#value'] = t('Agregar otra foto');
          $form['group_fotos']['#prefix'] = 
          '<h2>'.t('Paso 5: Fotos').'</h2><p>'.t('Sube las fotos del automóvil aquí, en formato JPG, GIF o PNG. Recuerda que las puedes subir después.').'</p>';
          $form['group_fotos']['field_imagenes']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">1</div><p>'.t('Fotos del vehículo').'</p></div>';
          $form['group_logo']['field_logo_agencia']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">2</div><p>'.t('Logotipo de agencia').'</p></div>';
          
          //print_r($form);exit;
        }
        break;

        
    /************************************
    *           CAMIONETAS              *
    ************************************/
    
      case 'camioneta_node_form':
    
        drupal_add_js(drupal_get_path('module', 'motores_anuncio').'/anuncio_engine.js', $type = 'module', 'header', FALSE, FALSE);
        
        //print_r($form);exit;
        
        // container div
        $form['#prefix'] = '<div class="anuncio600">';
        $form['#suffix'] = '</div>';
        
         if(arg(3)!=3){
        	unset($form['body_field']);
        }
        
        // botones
        unset($form['buttons']['save']);
        unset($form['buttons']['delete']);
        unset($form['buttons']['previous']);
        if (isset($form['buttons']['next']))
        { 
          $form['buttons']['next']['#value'] = t('Continuar');
        }
        else
        {
          $form['buttons']['done']['#value'] = t('Continuar');
          $form['#redirect'] = 'anuncio_preview/'.$form['#node']->nid;
        }
        
        
        
        /**********
        PASO 2
        **********/
        unset($form['field_tipo_anunio']);
        //$form['field_vigencia']['#type'] = 'hidden';
        $form['group_marca_modelo']['#prefix'] = '<h2>'.t('Paso 2: Marca y Modelo').'</h2>';
        $form['group_marca_modelo']['field_marca']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y modelo del vehículo que desea vender.').'</p></div>';
        $form['group_marca_modelo']['#suffix'] =
          '<fieldset>
            <div class="nn clear-block"><div class="num">2</div><p>'.t('Aceptar el reglamento de publicación de anuncios en Mercado Absoluto Vehículos.').'</p></div>
          
            <div class="form-item">
              <textarea id="eula" readonly="readonly">'.variable_get( 'motores_anuncio_eula', '' ).'</textarea>
              <input type="checkbox"/> '.t('He leído y acepto las condiciones del reglamento.').'
            </div>
          </fieldset>';
        
        
        /**********
        PASO 3
        **********/
        $form['group_anio_submodelo']['#prefix'] = '<h2>'.t('Paso 3: Año y Submodelo').'</h2>';
        $form['group_anio_submodelo']['field_anio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y sub-modelo del vehículo que desea:').'</p></div>';
        
        
        /**********
        PASO 4
        **********/
        $form['group_detalles']['#prefix'] = 
        '<h2>'.t('Paso 4: Detalles').'</h2><p>'.t('Llena los siguientes datos describiendo las características del vehículo que deseas vender.
        Los campos obligatorios se indican con').' (<span class="form-required">*</span>).</p>';
        $form['group_detalles']['field_precio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Datos del vehículo').'</p></div>';
         /* <div class="nn form-item clear-block">
          <div class="preview-field">Marca: </div>
          <div class="preview-field">Submodelo: <span>'.$form['#node']->field_version[0]['value'].'</span></div>
          <div class="preview-field">Modelo: </div>
          <div class="preview-field">Año: <span>'.$form['#node']->field_anio[0]['value'].'</span></div>
          </div>
          ';*/
         $form['body_field']['#prefix'] = '<fieldset><div class="nn clear-block"><div class="num">4</div><p>'.t('Describe tu camioneta').'</p></div>';
        $form['body_field']['#suffix'] = '</fieldset>';
        unset($form['body_field']['format']);
        
        $form['group_equipo']['field_cristales']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">2</div><p>'.t('Equipo').'</p></div>';
          
        $form['group_opciones']['field_especiales']['#prefix'] = 
         '<div class="nn clear-block"><div class="num">3</div><p>'.t('Opciones especiales de venta').'</p></div>';
        
        if (motores_anuncio_is_cuenta_agencia($user))
        {
          $form['group_liga']['field_liga_agencia']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">5</div><p>'.t('Proporciona la liga del sitio de tu agencia').'</p></div>';
        }
        else
        {
          unset($form['group_liga']);
        }
        
        /**********
        PASO 5
        **********/
        
        // las fotos se tratan especialmente
        if ( arg(3) != '4' )
        {
          unset( $form['group_fotos'] );
          unset( $form['group_logo'] );
        }
        else
        {
          // validar si puede subir logo de agencia
          if ( !(in_array('agencia nuevos', $user->roles) || in_array('agencia otros', $user->roles) ||
                in_array('agencia usados', $user->roles) || in_array('lote usados', $user->roles)) )
          {
            unset($form['group_logo']);
            unset($form['group_liga']);
          }
          
          $form['group_fotos']['field_imagenes']['field_imagenes_add_more']['#value'] = t('Agregar otra foto');
          $form['group_fotos']['#prefix'] = 
          '<h2>'.t('Paso 5: Fotos').'</h2><p>'.t('Sube las fotos del automóvil aquí, en formato JPG, GIF o PNG. Recuerda que las puedes subir después.').'</p>';
          $form['group_fotos']['field_imagenes']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">1</div><p>'.t('Fotos del vehículo').'</p></div>';
          $form['group_logo']['field_logo_agencia']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">2</div><p>'.t('Logotipo de agencia').'</p></div>';
          
          //print_r($form);exit;
        }
        break;
        
        
        
    /************************************
    *              EXTREMO              *
    ************************************/
    
      case 'extremo_node_form':
    
        drupal_add_js(drupal_get_path('module', 'motores_anuncio').'/anuncio_engine.js', $type = 'module', 'header', FALSE, FALSE);
        
        //print_r($form);exit;
        
        // container div
        $form['#prefix'] = '<div class="anuncio600">';
        $form['#suffix'] = '</div>';
        
       
         //print_r();
          //if(arg(3)!=3){
        	//unset($form['body_field']);
          //}
                
        // botones
        unset($form['buttons']['save']);
        unset($form['buttons']['delete']);
        unset($form['buttons']['previous']);
        if (isset($form['buttons']['next']))
        { 
          $form['buttons']['next']['#value'] = t('Continuar');
        }
        else
        {
          $form['buttons']['done']['#value'] = t('Continuar');
          $form['#redirect'] = 'anuncio_preview/'.$form['#node']->nid;
        }
        
        
        
        /**********
        PASO 2
        **********/
        unset($form['field_tipo_anunio']);
        //$form['field_vigencia']['#type'] = 'hidden';
        $form['group_marca_modelo']['#prefix'] = '<h2>'.t('Paso 2: Marca y Modelo').'</h2>';
        $form['group_marca_modelo']['field_marca_extremo']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y modelo del vehículo que desea vender.').'</p></div>';
        $form['group_marca_modelo']['#suffix'] =
          '<fieldset>
            <div class="nn clear-block"><div class="num">2</div><p>'.t('Aceptar el reglamento de publicación de anuncios en Mercado Absoluto Vehículos.').'</p></div>
          
            <div class="form-item">
              <textarea id="eula" readonly="readonly">'.variable_get( 'motores_anuncio_eula', '' ).'</textarea>
              <input type="checkbox"/> '.t('He leído y acepto las condiciones del reglamento.').'
            </div>
          </fieldset>';
        
        
        /**********
        PASO 3
        **********/
        $form['group_anio_submodelo']['#prefix'] = '<h2>'.t('Paso 3: Año y Submodelo').'</h2>';
        $form['group_anio_submodelo']['field_anio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y sub-modelo del vehículo que desea:').'</p></div>';
        
        
        /**********
        PASO 4
        **********/
        $form['group_detalles']['#prefix'] = 
        '<h2>'.t('Paso 4: Detalles').'</h2><p>'.t('Llena los siguientes datos describiendo las características del vehículo que deseas vender.
        Los campos obligatorios se indican con').' (<span class="form-required">*</span>).</p>';
        $form['group_detalles']['field_precio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Datos del vehículo').'</p></div>';
         /* <div class="nn form-item clear-block">
          <div class="preview-field">Marca: </div>
          <div class="preview-field">Submodelo: <span>'.$form['#node']->field_version[0]['value'].'</span></div>
          <div class="preview-field">Modelo: </div>
          <div class="preview-field">Año: <span>'.$form['#node']->field_anio[0]['value'].'</span></div>
          </div>
          ';*/
         $form['body_field']['#prefix'] = '<fieldset><div class="nn clear-block"><div class="num">4</div><p>'.t('Describe tu vehiculo extremo').'</p></div>';
        $form['body_field']['#suffix'] = '</fieldset>';
        unset($form['body_field']['format']);
        
        $form['group_equipo']['field_cristales']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">2</div><p>'.t('Equipo').'</p></div>';
          
        $form['group_opciones']['field_especiales']['#prefix'] = 
         '<div class="nn clear-block"><div class="num">3</div><p>'.t('Opciones especiales de venta').'</p></div>';
        
        if (motores_anuncio_is_cuenta_agencia($user))
        {
          $form['group_liga']['field_liga_agencia']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">5</div><p>'.t('Proporciona la liga del sitio de tu agencia').'</p></div>';
        }
        else
        {
          unset($form['group_liga']);
        }
        
        /**********
        PASO 5
        **********/
        
        // las fotos se tratan especialmente
        if ( arg(3) != '4' )
        {
          unset( $form['group_fotos'] );
          unset( $form['group_logo'] );
        }
        else
        {
          // validar si puede subir logo de agencia
          if ( !(in_array('agencia nuevos', $user->roles) || in_array('agencia otros', $user->roles) ||
                in_array('agencia usados', $user->roles) || in_array('lote usados', $user->roles)) )
          {
            unset($form['group_logo']);
            unset($form['group_liga']);
          }
          
          $form['group_fotos']['field_imagenes']['field_imagenes_add_more']['#value'] = t('Agregar otra foto');
          $form['group_fotos']['#prefix'] = 
          '<h2>'.t('Paso 5: Fotos').'</h2><p>'.t('Sube las fotos del automóvil aquí, en formato JPG, GIF o PNG. Recuerda que las puedes subir después.').'</p>';
          $form['group_fotos']['field_imagenes']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">1</div><p>'.t('Fotos del vehículo').'</p></div>';
          $form['group_logo']['field_logo_agencia']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">2</div><p>'.t('Logotipo de agencia').'</p></div>';
          
          //print_r($form);exit;
        }
        break;
        
    /************************************
    *              OTROS                *
    ************************************/
    
      case 'otros_node_form':
    
        drupal_add_js(drupal_get_path('module', 'motores_anuncio').'/anuncio_engine.js', $type = 'module', 'header', FALSE, FALSE);
        
        //print_r($form);exit;
        
        // container div
        $form['#prefix'] = '<div class="anuncio600">';
        $form['#suffix'] = '</div>';
        
         //print_r();
         if(arg(3)!=3){
        	unset($form['body_field']);
        }
        
        // botones
        unset($form['buttons']['save']);
        unset($form['buttons']['delete']);
        unset($form['buttons']['previous']);
        if (isset($form['buttons']['next']))
        { 
          $form['buttons']['next']['#value'] = t('Continuar');
        }
        else
        {
          $form['buttons']['done']['#value'] = t('Continuar');
          $form['#redirect'] = 'anuncio_preview/'.$form['#node']->nid;
        }
        
        
        
        /**********
        PASO 2
        **********/
        unset($form['field_tipo_anunio']);
        //$form['field_vigencia']['#type'] = 'hidden';
        $form['group_marca_modelo']['#prefix'] = '<h2>'.t('Paso 2: Marca y Modelo').'</h2>';
        $form['group_marca_modelo']['field_marca_otros']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y modelo del vehículo que desea vender.').'</p></div>';
        $form['group_marca_modelo']['#suffix'] =
          '<fieldset>
            <div class="nn clear-block"><div class="num">2</div><p>'.t('Aceptar el reglamento de publicación de anuncios en Mercado Absoluto Vehículos.').'</p></div>
          
            <div class="form-item">
              <textarea id="eula" readonly="readonly">'.variable_get( 'motores_anuncio_eula', '' ).'</textarea>
              <input type="checkbox"/> '.t('He leído y acepto las condiciones del reglamento.').'
            </div>
          </fieldset>';
        
        
        /**********
        PASO 3
        **********/
        $form['group_anio_submodelo']['#prefix'] = '<h2>'.t('Paso 3: Año y Submodelo').'</h2>';
        $form['group_anio_submodelo']['field_anio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Seleccione la marca y sub-modelo del vehículo que desea:').'</p></div>';
        
        
        /**********
        PASO 4
        **********/
        $form['group_detalles']['#prefix'] = 
        '<h2>'.t('Paso 4: Detalles').'</h2><p>'.t('Llena los siguientes datos describiendo las características del vehículo que deseas vender.
        Los campos obligatorios se indican con').' (<span class="form-required">*</span>).</p>';
        $form['group_detalles']['field_precio']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">1</div><p>'.t('Datos del vehículo').'</p></div>';
         /* <div class="nn form-item clear-block">
          <div class="preview-field">Marca: </div>
          <div class="preview-field">Submodelo: <span>'.$form['#node']->field_version[0]['value'].'</span></div>
          <div class="preview-field">Modelo: </div>
          <div class="preview-field">Año: <span>'.$form['#node']->field_anio[0]['value'].'</span></div>
          </div>
          ';*/
         $form['body_field']['#prefix'] = '<fieldset><div class="nn clear-block"><div class="num">4</div><p>'.t('Describe tu vehiculo extremo').'</p></div>';
        $form['body_field']['#suffix'] = '</fieldset>';
        unset($form['body_field']['format']);
        
        $form['group_equipo']['field_blindaje']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">2</div><p>'.t('Equipo').'</p></div>';
          
        $form['group_opciones']['field_especiales']['#prefix'] = 
         '<div class="nn clear-block"><div class="num">3</div><p>'.t('Opciones especiales de venta').'</p></div>';
        
        if (motores_anuncio_is_cuenta_agencia($user))
        {
          $form['group_liga']['field_liga_agencia']['#prefix'] = 
          '<div class="nn clear-block"><div class="num">5</div><p>'.t('Proporciona la liga del sitio de tu agencia').'</p></div>';
        }
        else
        {
          unset($form['group_liga']);
        }
        
        /**********
        PASO 5
        **********/
        
        // las fotos se tratan especialmente
        if ( arg(3) != '4' )
        {
          unset( $form['group_fotos'] );
          unset( $form['group_logo'] );
        }
        else
        {
          // validar si puede subir logo de agencia
          if ( !(in_array('agencia nuevos', $user->roles) || in_array('agencia otros', $user->roles) ||
                in_array('agencia usados', $user->roles) || in_array('lote usados', $user->roles)) )
          {
            unset($form['group_logo']);
            unset($form['group_liga']);
          }
          
          $form['group_fotos']['field_imagenes']['field_imagenes_add_more']['#value'] = t('Agregar otra foto');
          $form['group_fotos']['#prefix'] = 
          '<h2>'.t('Paso 5: Fotos').'</h2><p>'.t('Sube las fotos del automóvil aquí, en formato JPG, GIF o PNG. Recuerda que las puedes subir después.').'</p>';
          $form['group_fotos']['field_imagenes']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">1</div><p>'.t('Fotos del vehículo').'</p></div>';
          $form['group_logo']['field_logo_agencia']['#prefix'] = 
            '<div class="nn clear-block"><div class="num">2</div><p>'.t('Logotipo de agencia').'</p></div>';
          
          //print_r($form);exit;
        }
        break;    
        
        
        
    }
  }
}

/*
  Esta funcion se llama desde tarifas de vehiculos,
  valida si el usuario es una agencia, porque no debe mostrarle precios,
  nomas ir a crear el anuncio
*/
function motores_anuncio_validate_agencia()
{
  global $user;
  if ( in_array('agencia nuevos', $user->roles) || in_array('agencia otros', $user->roles) ||
        in_array('agencia usados', $user->roles) || in_array('lote usados', $user->roles) )
  {
    drupal_goto('anuncio/crear','p=agencia&t='.$_GET['t']);
  }
}

/*
  Revisa si el usuario ya tiene cuenta como para comenzar
  el proceso de anuncio
*/
function motores_anuncio_configure_cart()
{ 
  switch( $_GET['p'] )
  {
    case 'gratuito':
      $anuncio = '63';
    break;
    case 'basico':
      $anuncio = '53';
    break;
    case 'premium':
      $anuncio = '64';
    break;
    case 'agencia':
      $anuncio = '77';
    break;
  }
  
  global $user;
  
  if ( $user->uid )
  {
    // start creating the ad
    $cid = uc_cart_get_id();
    uc_cart_empty($cid);
    uc_cart_add_item($anuncio);
    
    drupal_goto('node/add/'.$_GET['t']);
  }
  else
  {
    // nel, registrate primero
    drupal_goto('user/register','p='.$anuncio.'&t='.$_GET['t']);
  }
}

/**
 * Modifica datos del usuario para vigencias y todo al momento de
 * hacer user_load
 */
function motores_anuncio_user( $op, &$edit, &$account )
{
  switch ($op)
  {
    case 'insert':
    
      //
      // Mantiene el anuncio elegido por el usuario si el sistema
      // le pide registrarse primero
      //
      
      if ( isset($_GET['p']) && $prod = $_GET['p'] )
      {
        // agrega el anuncio al carrito
        $cid = uc_cart_get_id();
        uc_cart_empty($cid);
        uc_cart_add_item($prod);
        
        // ahora si a darle al anuncio
        drupal_goto('node/add/'.$_GET['t']);
      }
    break;
    
    case 'load':
    
      //
      // Calcula la fecha de vigencia de todos los anuncios de una agencia
      // o lote
      //
      // $user->vigencia   = fecha de vigencia del pago
      // $user->vencido    = bandera de vencido o no
      // $user->diezdias   = bandera de si son 10 dias antes del vencimiento (dashboard)
      //
      $account->cuenta_agencia = motores_anuncio_is_cuenta_agencia($account);
      if ( $account->cuenta_agencia )
      {
        
        $pago = mktime(0,0,0,$account->profile_ultimo_pago['month'],
          $account->profile_ultimo_pago['day'], $account->profile_ultimo_pago['year']);
          
        switch ( $account->profile_periodo_pago )
        {
          case 'Semestral':
          
            $vence = strtotime( '+6 months' , $pago );
            $vencediez = strtotime( '-10 days' , $vence );
            
            $account->vigencia = date( 'M/d/Y', $vence );
            $account->vencido = ( time() > $vence );
            $account->diezdias = ( time() > $vencediez );
          
          break;
          case 'Mensual':
            
            $vence = strtotime( '+1 month' , $pago );
            $vencediez = strtotime( '-10 days' , $vence );
            
            $account->vigencia = date( 'M/d/Y', $vence );
            $account->vencido = ( time() > $vence );
            $account->diezdias = ( time() > $vencediez );
            
          break;
          case 'Anual':
          
            $vence = strtotime( '+1 year' , $pago );
            $vencediez = strtotime( '-10 days' , $vence );
            
            $account->vigencia = date( 'M/d/Y', $vence );
            $account->vencido = ( time() > $vence );
            $account->diezdias = ( time() > $vencediez );
            
          break;
        }
      }
      //print_r($account);
    break;
  }
}

/**
 * Modifica datos de anuncios para vigencias y todo al momento de
 * hacer node_load
 */
function motores_anuncio_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{

  /**
   * Cuando se cree un anuncio, asociarle correctamente la taxonomia de marca
   * y modelo, para que tenga todos los terminos (ej. "Audi"+"A3" en vez de solamente "A3")
   */
  if ($op == 'insert')
  {
    switch ($node->type)
    {
      case 'carro': // vocabulario: Marca-carro, vid: 3
      
      $modelo = $node->taxonomy[3][0];
      $marca = taxonomy_get_parents($modelo);
      $args = array_keys($marca);
      //taxonomy_node_save($node, $args);
      $node->field_marca[] = $node->field_marca[0];
      $node->field_marca[0] = array('value'=>$args[0]);
      node_save($node);
      break;
      
      
      case 'moto': // vocabulario: Marca-moto, vid: 4
      
      $modelo = $node->taxonomy[4][0];
      $marca = taxonomy_get_parents($modelo);
      $args = array_keys($marca);
      //taxonomy_node_save($node, $args);
      $node->field_marca[] = $node->field_marca[0];
      $node->field_marca[0] = array('value'=>$args[0]);
      node_save($node);
      break;
    
    
     case 'camioneta': // vocabulario: Marca-moto, vid: 3
      
      $modelo = $node->taxonomy[3][0];
      $marca = taxonomy_get_parents($modelo);
      $args = array_keys($marca);
      //taxonomy_node_save($node, $args);
      $node->field_marca[] = $node->field_marca[0];
      $node->field_marca[0] = array('value'=>$args[0]);
      node_save($node);
      break;
    
    
     case 'lancha': // vocabulario: Marca-moto, vid: 5
      
      $modelo = $node->taxonomy[5][0];
      $marca = taxonomy_get_parents($modelo);
      $args = array_keys($marca);
      //taxonomy_node_save($node, $args);
      $node->field_marca[] = $node->field_marca[0];
      $node->field_marca[0] = array('value'=>$args[0]);
      node_save($node);
      break;
    
    
     case 'extremo': // vocabulario: Marca-moto, vid: 9
      
      $modelo = $node->taxonomy[9][0];
      $marca = taxonomy_get_parents($modelo);
      $args = array_keys($marca);
      //taxonomy_node_save($node, $args);
      $node->field_marca[] = $node->field_marca[0];
      $node->field_marca[0] = array('value'=>$args[0]);
      node_save($node);
      break;
    
    
     case 'otros': // vocabulario: Marca-moto, vid: 8
      
      $modelo = $node->taxonomy[8][0];
      $marca = taxonomy_get_parents($modelo);
      $args = array_keys($marca);
      //taxonomy_node_save($node, $args);
      $node->field_marca[] = $node->field_marca[0];
      $node->field_marca[0] = array('value'=>$args[0]);
      node_save($node);
      break;
    
    }
  }

	if ($op == 'load')
	{
  	switch ($node->type)
  	{
  	  case 'carro':
  	  
  	    //
  	    // Carga nombre de carro con taxonomia y anio 
  	    //
  	    $node->nombre = $node->field_anio[0]['value'];
  	    $node->nombre_sin_anio = '';

  	    $carro = array();
  	    foreach ( $node->field_marca as $m )
  	    {
  	      $c = taxonomy_get_term($m['value']);
  	      $carro[] = $c->name;
  	    }
  	    $node->nombre .= ' '.implode(' ', $carro);
  	    $node->nombre_sin_anio .= implode(' ', $carro);
  	    
  	    //
  	    // Calcula la fecha de vigencia de todos los anuncios 
  	    //
  	    switch($node->field_tipo_anunio[0]['nid'])
  	    {
	        case 63: //gratuito, 30 dias
	          
	          $vence = strtotime( '+30 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	          
	        break;
	        case 53: //basico, 60 dias
	          
	          $vence = strtotime( '+60 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	          
	        break;
	        default: // premium
	    
	          $vence = strtotime( '+30 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	    
	        break;	
  	    }
  	    //$node->vencimiento
  	    
  	  break;
  	  
  	  case 'moto':
  	  
  	    //
  	    // Carga nombre de carro con taxonomia y anio 
  	    //
  	    $node->nombre = $node->field_anio[0]['value'];
  	    $node->nombre_sin_anio = '';

  	    $moto = array();
  	    foreach ( $node->field_marca as $m )
  	    {
  	      $c = taxonomy_get_term($m['value']);
  	      $moto[] = $c->name;
  	    }
  	    $node->nombre .= ' '.implode(' ', $moto);
  	    $node->nombre_sin_anio .= implode(' ', $moto);
  	    
  	    //
  	    // Calcula la fecha de vigencia de todos los anuncios 
  	    //
  	    switch($node->field_tipo_anunio[0]['nid'])
  	    {
	        case 63: //gratuito, 30 dias
	          
	          $vence = strtotime( '+30 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	          
	        break;
	        case 53: //basico, 60 dias
	          
	          $vence = strtotime( '+60 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	          
	        break;
	        default: // premium
	    
	          $vence = strtotime( '+30 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	    
	        break;	
  	    }
  	    //$node->vencimiento
  	    
  	  break;
  	  
  	  
  	  case 'camioneta':
  	  case 'lancha':
  	  case 'extremo':
  	  case 'otros':
  	  
  	    //
  	    // Carga nombre de carro con taxonomia y anio 
  	    //
  	    $node->nombre = $node->field_anio[0]['value'];
  	    $node->nombre_sin_anio = '';

  	    $camioneta = array();
  	    foreach ( $node->field_marca as $m )
  	    {
  	      $c = taxonomy_get_term($m['value']);
  	      $camioneta[] = $c->name;
  	    }
  	    $node->nombre .= ' '.implode(' ', $camioneta);
  	    $node->nombre_sin_anio .= implode(' ', $camioneta);
  	    
  	    //
  	    // Calcula la fecha de vigencia de todos los anuncios 
  	    //
  	    switch($node->field_tipo_anunio[0]['nid'])
  	    {
	        case 63: //gratuito, 30 dias
	          
	          $vence = strtotime( '+30 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	          
	        break;
	        case 53: //basico, 60 dias
	          
	          $vence = strtotime( '+60 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	          
	        break;
	        default: // premium
	    
	          $vence = strtotime( '+30 days' , $node->field_vigencia[0]['value'] );
	          $node->vigencia = date( 'M/d/Y', $vence );
	          $node->vencido = ( $vence > time() ) ? false : true;
	    
	        break;	
  	    }
  	    //$node->vencimiento
  	    
  	  break;

  	}
	}
}

/**
 * Calcula si la cuenta de un usuario es de tipo agencia o normalita
 */
function motores_anuncio_is_cuenta_agencia($user)
{
  return (in_array('agencia nuevos', $user->roles) || 
    in_array('agencia usados', $user->roles) ||
    in_array('agencia otros', $user->roles) ||
    in_array('lote usados', $user->roles));
}

/**
 * Imprime la fecha de expedicion en el dashboard
 * depende de que tipo de cuenta sea
 */
function motores_anuncio_print_fecha_expedicion($data)
{
  global $user;
  
  if (motores_anuncio_is_cuenta_agencia($user))
  {
    $agencia = user_load($user->uid);
    $pago = mktime(0,0,0,$account->profile_ultimo_pago['month'],
      $account->profile_ultimo_pago['day'], $account->profile_ultimo_pago['year']);
      
    return date('M/d/Y', $pago);
  }
  else
  {
    return date('M/d/Y', $data->node->field_vigencia[0]['value']);
    
  }
}

/**
 * Imprime el monto a pagar en dashboard
 * se fija si faltan diez dias o ya es la fecha de vencimiento de anuncio o cuenta
 * y te dice cuanto hay que pagar
 */
function motores_anuncio_print_monto_a_pagar($data)
{
  global $user;
  
  if (motores_anuncio_is_cuenta_agencia($user))
  {
    $agencia = user_load($user->uid);
    if ($agencia->diezdias)
    {
      // obtener el precio a pagar
      if (in_array('agencia usados', $agencia->roles)) $rol = 'usados';
      if (in_array('agencia nuevos', $agencia->roles)) $rol = 'nuevos';
      if (in_array('lote usados', $agencia->roles)) $rol = 'lote';
      if (in_array('agencia otros', $agencia->roles)) $rol = 'otros';
      $precio_var = 'precio_'.$rol.'_'.$agencia->profile_num_anuncios.'_'.strtolower($agencia->profile_periodo_pago);
      
      // display
      $r = '<div class="deuda"><span class="red">$'.variable_get($precio_var,'').'</span>';
      $r .= '<br/>Pago '.$agencia->profile_periodo_pago.'<br/>Realiza tu pago</div>';
    }
    else
    {
      $r .= '<span class="green">$0.00</span>';
    }
    return $r;
  }
  else
  {
    $sku = $data->node_node_data_field_tipo_anunio__uc_products_model;
    $dist = strtotime( '+30 day', $data->node_created );
    
    if ( !$data->node->vencido ) 
    {
      return '<span class="green">$0.00</span>';
    }
    else
    {
      $r = '<div class="deuda"><span class="red">$'.variable_get('precio_anuncio_reposicion','').'</span>';
      $r .= '<br/>Realiza tu pago</div>';
      
      return $r;
    }
    
  }
}

/**
 * Elimina anuncios desde el dashboard
 */
function motores_anuncio_borrar()
{
  $nids = explode(',', $_GET['nids']);
  array_pop($nids);
  
  foreach ($nids as $n)
  {
    node_delete($n);
  }
  drupal_goto('micuenta');
}

/**
 * Implementation of hook_views_api().
 */
function motores_anuncio_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'motores_anuncio'),
    //'path' => drupal_get_path('module', 'motores_anuncio') . '/includes',
  );
}