<?php

/*****************************
  HOOKS
*****************************/
function motores_admin_menu()
{
  // Items disponibles en el menu
  $items['admin/motores_admin'] = array(
    'title' => t('Administrar Todo de Motores'),
    'page callback' => 'motores_admin_main_menu',
    'access arguments' => array('administer todo de motores'),
  );
  $items['admin/motores_admin/anuncios'] = array(
    'title' => t('Lista de control de Anuncios'),
    'page callback' => 'motores_admin_main_menu',
    'access arguments' => array('administer todo de motores'),
  );
  $items['admin/motores_admin/agencias'] = array(
    'title' => t('Lista de control de Agencias y lotes'),
    'page callback' => 'motores_admin_main_menu_lotes',
    'access arguments' => array('administer todo de motores'),
  );
  $items['admin/motores_admin/precios'] = array(
    'title' => t('Tabla de precios'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('motores_admin_precios'),
    'access arguments' => array('administer todo de motores'),
  );
  
  // Callbacks
  $items['motores_admin/unpublish'] = array(
    'page callback' => 'motores_admin_despublicar',
    'access arguments' => array('administer todo de motores'),
    'type' => MENU_CALLBACK
  );
  $items['motores_admin/unpublish_user'] = array(
    'page callback' => 'motores_admin_despublicar_user',
    'access arguments' => array('administer todo de motores'),
    'type' => MENU_CALLBACK
  );
  $items['motores_admin/publish'] = array(
    'page callback' => 'motores_admin_publicar',
    'access arguments' => array('administer todo de motores'),
    'type' => MENU_CALLBACK
  );
  $items['motores_admin/publish_user'] = array(
    'page callback' => 'motores_admin_publicar_user',
    'access arguments' => array('administer todo de motores'),
    'type' => MENU_CALLBACK
  );
  $items['motores_admin/delete_user'] = array(
    'title' => t('Eliminar cuenta'),
    'page callback' => 'motores_admin_eliminar_user',
    'access arguments' => array('administer todo de motores'),
    'type' => MENU_CALLBACK
  );
  $items['motores_admin/delete_user_proc'] = array(
    'page callback' => 'motores_admin_eliminar_user_proc',
    'access arguments' => array('administer todo de motores'),
    'type' => MENU_CALLBACK
  );
  
  return $items;
}

function motores_admin_perm()
{
  return array('administer todo de motores');
}

function motores_admin_init()
{
  global $custom_theme;
  if ( arg(1) == 'delete_user' )
  {
    $custom_theme = variable_get('admin_theme', '0');
    init_theme();
  }
}

/**
 * Implementation of hook_views_api().
 */
function motores_admin_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'motores_admin'),
    //'path' => drupal_get_path('module', 'motores_admin') . '/includes',
  );
}

/*****************************
  MAIN MENU
*****************************/
function motores_admin_main_menu()
{
  drupal_goto('admin/control_anuncios');
}
function motores_admin_main_menu_lotes()
{
  drupal_goto('admin/control_agencias');
}

/*****************************
  PROCESAMIENTO DE PRECIOS
*****************************/

function motores_admin_precios()
{
  $form = array();
  
  $form['vehiculos'] = array(
    '#type' => 'fieldset',
    '#title' => t('Vehículos'),
    '#description' => t('Indique las cantidades sin símbolos ni puntos ni comas')
  );
  $form['vehiculos']['precio_anuncio_basico'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_anuncio_basico', '100' ),
    '#title' => t('Precio de anuncio básico')
  );
  $form['vehiculos']['precio_anuncio_premium'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_anuncio_premium', '230' ),
    '#title' => t('Precio de anuncio premium')
  );
  $form['vehiculos']['precio_anuncio_reposicion'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_anuncio_reposicion', '90' ),
    '#title' => t('Costo de reposición')
  );
  
  
  
  
  
  
  
  $form['agencias_usados'] = array(
    '#type' => 'fieldset',
    '#title' => t('Agencias de autos usados')
  );
  
  $form['agencias_usados']['a_10'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('10 anuncios')
  );
  $form['agencias_usados']['a_10']['precio_usados_10_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_10_mensual', '1000' ),
    '#title' => t('Mensual')
  );
  $form['agencias_usados']['a_10']['precio_usados_10_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_10_semestral', '5400' ),
    '#title' => t('Semestral')
  );
  $form['agencias_usados']['a_10']['precio_usados_10_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_10_anual', '10200' ),
    '#title' => t('Anual')
  );
  
  $form['agencias_usados']['a_25'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('25 anuncios')
  );
  $form['agencias_usados']['a_25']['precio_usados_25_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_25_mensual', '1250' ),
    '#title' => t('Mensual')
  );
  $form['agencias_usados']['a_25']['precio_usados_25_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_25_semestral', '6750' ),
    '#title' => t('Semestral')
  );
  $form['agencias_usados']['a_25']['precio_usados_25_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_25_anual', '12750' ),
    '#title' => t('Anual')
  );
  
  $form['agencias_usados']['a_35'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('35 anuncios')
  );
  $form['agencias_usados']['a_35']['precio_usados_35_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_35_mensual', '1500' ),
    '#title' => t('Mensual')
  );
  $form['agencias_usados']['a_35']['precio_usados_35_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_35_semestral', '8100' ),
    '#title' => t('Semestral')
  );
  $form['agencias_usados']['a_35']['precio_usados_35_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_35_anual', '15300' ),
    '#title' => t('Anual')
  );
  
  $form['agencias_usados']['a_50'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('50 anuncios')
  );
  $form['agencias_usados']['a_50']['precio_usados_50_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_50_mensual', '2300' ),
    '#title' => t('Mensual')
  );
  $form['agencias_usados']['a_50']['precio_usados_50_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_50_semestral', '12420' ),
    '#title' => t('Semestral')
  );
  $form['agencias_usados']['a_50']['precio_usados_50_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_50_anual', '23460' ),
    '#title' => t('Anual')
  );
  
  $form['agencias_usados']['a_100'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('100 anuncios')
  );
  $form['agencias_usados']['a_100']['precio_usados_100_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_100_mensual', '4300' ),
    '#title' => t('Mensual')
  );
  $form['agencias_usados']['a_100']['precio_usados_100_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_100_semestral', '25800' ),
    '#title' => t('Semestral')
  );
  $form['agencias_usados']['a_100']['precio_usados_100_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_100_anual', '43860' ),
    '#title' => t('Anual')
  );
  
  $form['agencias_usados']['precio_usados_membresia'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_usados_membresia', '6500' ),
    '#title' => t('Membresía única')
  );
  
  
  
  
  
  
  
  
  $form['agencias_nuevos'] = array(
    '#type' => 'fieldset',
    '#title' => t('Agencias de autos nuevos')
  );
  
  $form['agencias_nuevos']['a_75'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('75 anuncios')
  );
  $form['agencias_nuevos']['a_75']['precio_nuevos_75_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_nuevos_75_mensual', '3100' ),
    '#title' => t('Mensual')
  );
  $form['agencias_nuevos']['a_75']['precio_nuevos_75_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_nuevos_75_semestral', '15810' ),
    '#title' => t('Semestral')
  );
  $form['agencias_nuevos']['a_75']['precio_nuevos_75_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_nuevos_75_anual', '26040' ),
    '#title' => t('Anual')
  );
  
  $form['agencias_nuevos']['precio_nuevos_membresia'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_nuevos_membresia', '5500' ),
    '#title' => t('Membresía única')
  );
  
  
  
  
  
  $form['lote_usados'] = array(
    '#type' => 'fieldset',
    '#title' => t('Lote de autos usados')
  );
  
  $form['lote_usados']['a_10'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('10 anuncios')
  );
  $form['lote_usados']['a_10']['precio_lote_10_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_10_mensual', '1000' ),
    '#title' => t('Mensual')
  );
  $form['lote_usados']['a_10']['precio_lote_10_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_10_semestral', '5400' ),
    '#title' => t('Semestral')
  );
  $form['lote_usados']['a_10']['precio_lote_10_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_10_anual', '10200' ),
    '#title' => t('Anual')
  );
  
  $form['lote_usados']['a_25'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('25 anuncios')
  );
  $form['lote_usados']['a_25']['precio_lote_25_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_25_mensual', '1250' ),
    '#title' => t('Mensual')
  );
  $form['lote_usados']['a_25']['precio_lote_25_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_25_semestral', '6750' ),
    '#title' => t('Semestral')
  );
  $form['lote_usados']['a_25']['precio_lote_25_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_25_anual', '12750' ),
    '#title' => t('Anual')
  );
  
  $form['lote_usados']['a_35'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('35 anuncios')
  );
  $form['lote_usados']['a_35']['precio_lote_35_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_35_mensual', '1500' ),
    '#title' => t('Mensual')
  );
  $form['lote_usados']['a_35']['precio_lote_35_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_35_semestral', '8100' ),
    '#title' => t('Semestral')
  );
  $form['lote_usados']['a_35']['precio_lote_35_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_35_anual', '15300' ),
    '#title' => t('Anual')
  );
  
  $form['lote_usados']['a_50'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('50 anuncios')
  );
  $form['lote_usados']['a_50']['precio_lote_50_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_50_mensual', '2300' ),
    '#title' => t('Mensual')
  );
  $form['lote_usados']['a_50']['precio_lote_50_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_50_semestral', '12420' ),
    '#title' => t('Semestral')
  );
  $form['lote_usados']['a_50']['precio_lote_50_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_50_anual', '23460' ),
    '#title' => t('Anual')
  );
  
  $form['lote_usados']['a_100'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('100 anuncios')
  );
  $form['lote_usados']['a_100']['precio_lote_100_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_100_mensual', '4300' ),
    '#title' => t('Mensual')
  );
  $form['lote_usados']['a_100']['precio_lote_100_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_100_semestral', '25800' ),
    '#title' => t('Semestral')
  );
  $form['lote_usados']['a_100']['precio_lote_100_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_100_anual', '43860' ),
    '#title' => t('Anual')
  );
  
  $form['lote_usados']['precio_lote_membresia'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_lote_membresia', '2750' ),
    '#title' => t('Membresía única')
  );
  
  
  
  
  
  
  $form['agencia_otros'] = array(
    '#type' => 'fieldset',
    '#title' => t('Agencias de otro tipo de vehículos')
  );
  
  $form['agencia_otros']['a_10'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('10 anuncios')
  );
  $form['agencia_otros']['a_10']['precio_otros_10_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_10_mensual', '1000' ),
    '#title' => t('Mensual')
  );
  $form['agencia_otros']['a_10']['precio_otros_10_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_10_semestral', '5400' ),
    '#title' => t('Semestral')
  );
  $form['agencia_otros']['a_10']['precio_otros_10_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_10_anual', '10200' ),
    '#title' => t('Anual')
  );
  
  $form['agencia_otros']['a_25'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('25 anuncios')
  );
  $form['agencia_otros']['a_25']['precio_otros_25_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_25_mensual', '1250' ),
    '#title' => t('Mensual')
  );
  $form['agencia_otros']['a_25']['precio_otros_25_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_25_semestral', '6750' ),
    '#title' => t('Semestral')
  );
  $form['agencia_otros']['a_25']['precio_otros_25_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_25_anual', '12750' ),
    '#title' => t('Anual')
  );
  
  $form['agencia_otros']['a_35'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('35 anuncios')
  );
  $form['agencia_otros']['a_35']['precio_otros_35_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_35_mensual', '1500' ),
    '#title' => t('Mensual')
  );
  $form['agencia_otros']['a_35']['precio_otros_35_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_35_semestral', '8100' ),
    '#title' => t('Semestral')
  );
  $form['agencia_otros']['a_35']['precio_otros_35_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_35_anual', '15300' ),
    '#title' => t('Anual')
  );
  
  $form['agencia_otros']['a_50'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('50 anuncios')
  );
  $form['agencia_otros']['a_50']['precio_otros_50_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_50_mensual', '2300' ),
    '#title' => t('Mensual')
  );
  $form['agencia_otros']['a_50']['precio_otros_50_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_50_semestral', '12420' ),
    '#title' => t('Semestral')
  );
  $form['agencia_otros']['a_50']['precio_otros_50_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_50_anual', '23460' ),
    '#title' => t('Anual')
  );
  
  $form['agencia_otros']['a_100'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('100 anuncios')
  );
  $form['agencia_otros']['a_100']['precio_otros_100_mensual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_100_mensual', '4300' ),
    '#title' => t('Mensual')
  );
  $form['agencia_otros']['a_100']['precio_otros_100_semestral'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_100_semestral', '25800' ),
    '#title' => t('Semestral')
  );
  $form['agencia_otros']['a_100']['precio_otros_100_anual'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_100_anual', '43860' ),
    '#title' => t('Anual')
  );
  
  $form['agencia_otros']['precio_otros_membresia'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get( 'precio_otros_membresia', '2750' ),
    '#title' => t('Membresía única')
  );
  
  
  
  
  
  
  
  return system_settings_form( $form );
}

// Actualizar precios de anuncios de vehiculos en Drupal cuando los cambia el admin
function motores_admin_precios_validate( $form, &$form_state )
{
  $basico = $form_state['values']['precio_anuncio_basico'];
  $premium = $form_state['values']['precio_anuncio_premium'];
  
  // basico
  $basico_n = node_load('53');
  $basico_n->sell_price = $basico;
  node_save($basico_n);
  
  // basico
  $premium_n = node_load('64');
  $premium_n->sell_price = $premium;
  node_save($premium_n);
}

/*****************************
  PROCESAMIENTO DE USUARIOS Y CUENTAS
*****************************/
function motores_admin_despublicar()
{
  $node = node_load(arg(2));
  $node->status = 0;
  node_save($node);
  drupal_set_message(t('Anuncio %anuncio despublicado', array('%anuncio'=>'A-'.$node->nid)));
  drupal_goto($_GET['destination']);
}
function motores_admin_publicar()
{
  $node = node_load(arg(2));
  $node->status = 1;
  node_save($node);
  drupal_set_message(t('Anuncio %anuncio publicado', array('%anuncio'=>'A-'.$node->nid)));
  drupal_goto($_GET['destination']);
}
function motores_admin_despublicar_user()
{
  $sql = 
  "SELECT n.nid, n.title 
  FROM {node} n 
  WHERE n.uid = %d";
  $db_result = db_query(db_rewrite_sql($sql), arg(2));
  
  while ($term = db_fetch_object($db_result)) 
  {
    $node = node_load($term->nid);
    $node->status = 0;
    node_save($node);
  }
  
  drupal_set_message(t('Anuncios de usuario %user despublicados', array('%user'=>'C-'.arg(2))));
  drupal_goto($_GET['destination']);
}
function motores_admin_publicar_user()
{
  $sql = 
  "SELECT n.nid, n.title 
  FROM {node} n 
  WHERE n.uid = %d";
  $db_result = db_query(db_rewrite_sql($sql), arg(2));
  
  while ($term = db_fetch_object($db_result)) 
  {
    $node = node_load($term->nid);
    $node->status = 1;
    node_save($node);
  }
  
  drupal_set_message(t('Anuncios de usuario %user publicados. No olvide actualizar la fecha de último pago del usuario.', array('%user'=>'C-'.arg(2))));
  drupal_goto($_GET['destination']);
}
function motores_admin_eliminar_user_proc()
{
  $uid = arg(2);
  
  $sql = 
  "SELECT n.nid, n.title 
  FROM {node} n 
  WHERE n.uid = %d";
  $db_result = db_query(db_rewrite_sql($sql), $uid);
  
  while ($term = db_fetch_object($db_result)) 
  {
    node_delete($term->nid);
  }
  
  // dale gas al usuario...
  user_delete(array(),arg(2));
  
  drupal_set_message(t('Usuario %user y anuncios asociados eliminados.', array('%user'=>'C-'.arg(2))));
  drupal_goto($_GET['destination']);
}
function motores_admin_eliminar_user()
{
  $r = "<p>".t('Est&aacute; seguro de que quiere eliminar la cuenta %uid? Todos sus anuncios serán eliminados para siempre también.',
        array('%uid'=>'C-'.arg(2)))."</p><p>".l('Eliminar usuario y anuncios','motores_admin/delete_user_proc/'.arg(2),array('query'=>'destination='.$_GET['destination']))."</p>";
  return $r;
}